{
  "hash": "aad77dc699b0a16c436a719329750920",
  "result": {
    "markdown": "---\ntitle: \"Other: Interrupted TS/ARFIMA/Spectral Analysis\"\nformat:  \n  html:\n   embed-resources: true\n   code-fold: true\n---\n\n::: {.cell}\n\n:::\n\n\n# 1. Interrupted Time Series\n\nGiven the profound disruptions caused by the COVID-19 pandemic, which has significantly interrupted daily life and global events, employing an interrupted time series analysis is particularly apt. This method allows us to quantitatively assess the pandemic's impact on key socio-economic indicators. In our project, we have chosen to focus on Pfizer stock prices and GDP per capita as two pivotal metrics. By analyzing these indicators, we aim to capture and understand the extent of COVID-19's effects on both the corporate sector, specifically pharmaceuticals, and broader economic health. This approach will enable us to isolate the direct impacts of the pandemic from other variables and gain insights into the resilience and responsiveness of different economic sectors during such global crises. In these examples, we all selected 2020 February 20th as the treatment date to research.\n\n## 1.1 GDP Per Capita\n\n::: {.cell}\n\n```{.r .cell-code}\ngdp <- read_csv('Datasets/gdp.csv')\n\n# Convert DATE column from m/d/yy format to Date object and reformat to \"Year\" only for simplicity\ngdp$DATE <- format(mdy(gdp$DATE), \"%Y/%m/%d\")\n\n# Convert GDP column to numeric (floating-point) format if not already\ngdp$GDP <- as.numeric(gdp$GDP)\n\n# Visualize the plot\nstart_year <- year(min(gdp$DATE))\nstart_month <- month(min(gdp$DATE))\nend_year <- year(max(gdp$DATE))\nend_month <- month(max(gdp$DATE))\n\n# Calculate the number of observations from start to end\nnum_obs <- (end_year - start_year) * 4 + ceiling((end_month - start_month) / 3)\n\n\n# data glimpse\nhead(gdp, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  DATE          GDP\n  <chr>       <dbl>\n1 2017/01/01 19280.\n2 2017/04/01 19439.\n3 2017/07/01 19693.\n```\n:::\n\n```{.r .cell-code}\nfig <- plot_ly(gdp, x = ~DATE, y = ~GDP,name = 'GDP Per Capita', type = 'scatter', mode = 'lines')\n\nfig\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-2e202e69e2c94dbc007a\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-2e202e69e2c94dbc007a\">{\"x\":{\"visdat\":{\"cd6237d85baa\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"cd6237d85baa\",\"attrs\":{\"cd6237d85baa\":{\"x\":{},\"y\":{},\"mode\":\"lines\",\"name\":\"GDP Per Capita\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"DATE\",\"type\":\"category\",\"categoryorder\":\"array\",\"categoryarray\":[\"2017/01/01\",\"2017/04/01\",\"2017/07/01\",\"2017/10/01\",\"2018/01/01\",\"2018/04/01\",\"2018/07/01\",\"2018/10/01\",\"2019/01/01\",\"2019/04/01\",\"2019/07/01\",\"2019/10/01\",\"2020/01/01\",\"2020/04/01\",\"2020/07/01\",\"2020/10/01\",\"2021/01/01\",\"2021/04/01\",\"2021/07/01\",\"2021/10/01\",\"2022/01/01\",\"2022/04/01\",\"2022/07/01\",\"2022/10/01\",\"2023/01/01\",\"2023/04/01\",\"2023/07/01\",\"2023/10/01\"]},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"GDP\"},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[\"2017/01/01\",\"2017/04/01\",\"2017/07/01\",\"2017/10/01\",\"2018/01/01\",\"2018/04/01\",\"2018/07/01\",\"2018/10/01\",\"2019/01/01\",\"2019/04/01\",\"2019/07/01\",\"2019/10/01\",\"2020/01/01\",\"2020/04/01\",\"2020/07/01\",\"2020/10/01\",\"2021/01/01\",\"2021/04/01\",\"2021/07/01\",\"2021/10/01\",\"2022/01/01\",\"2022/04/01\",\"2022/07/01\",\"2022/10/01\",\"2023/01/01\",\"2023/04/01\",\"2023/07/01\",\"2023/10/01\"],\"y\":[19280.084,19438.643,19692.595,20037.088,20328.553,20580.912,20798.73,20917.867,21104.133,21384.775,21694.282,21902.39,21706.513,19913.143,21647.64,22024.502,22600.185,23292.362,23828.973,24654.603,25029.116,25544.273,25994.639,26408.405,26813.601,27063.012,27610.128,27944.627],\"mode\":\"lines\",\"name\":\"GDP Per Capita\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n\n```{.r .cell-code}\n# Create the time series object\n#gdp_ts <- ts(gdp$GDP, start = c(start_year, start_month), frequency = 4, deltat = 0.25)\n\ndataTS <-data.frame(\"Y\"=gdp$GDP)\ndataTS$Ts<-seq(1:length(gdp$GDP))\ndataTS$D <- ifelse(gdp$DATE < as.Date(\"2020-02-20\"), 0, 1)\ndataTS$P<- seq_along(gdp$DATE)\ndataTS$P[gdp$DATE < as.Date(\"2020-02-20\")] <- 0\n\nhead(dataTS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Y Ts D P\n1 19280.08  1 0 0\n2 19438.64  2 0 0\n3 19692.60  3 0 0\n4 20037.09  4 0 0\n5 20328.55  5 0 0\n6 20580.91  6 0 0\n```\n:::\n\n```{.r .cell-code}\nindex_of_2020_02_20 <- which(gdp$DATE == as.Date(\"2020-04-01\"))\n#index_of_2020_02_20 #14\n\nplot( dataTS$Ts, dataTS$Y,\n      bty=\"n\", pch=19, col=\"gray\",\n      xlab = \"Time\", \n      ylab = \"GDP Per Capita\" )\n\n# Line marking the interruption\nabline( v=13, col=\"firebrick\", lty=2 )\ntext( 9, 24000, \"Start of COVID\", col=\"firebrick\", cex=1.3, pos=4 )\n\n# Add the regression line\nts <- lm( Y ~ Ts + D + P, data=dataTS )\nlines( dataTS$Ts, ts$fitted.values, col=\"steelblue\", lwd=2 )\n```\n\n::: {.cell-output-display}\n![](other_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n:::\n\n- **Pre-COVID Trend**: Prior to the dashed red line labeled \"Start of COVID,\" there is a positive trend in GDP per capita, indicating economic growth. This is represented by the blue line, which is the fitted line from a regression model, showing the upward trajectory of GDP per capita over time.\n\n- **COVID-19 Impact**: The dashed red line signifies the point at which the COVID-19 pandemic began. Following this line, there's a noticeable dip in GDP per capita, reflecting the immediate economic impact of the pandemic. This downturn signifies a break from the previous growth trend.\n\n- **Post-COVID Recovery**: After the initial dip, the blue fitted line indicates that GDP per capita began to recover, continuing on an upward trajectory, although starting from a lower point than where the pre-COVID trend would have predicted.\n\n- **Recovery Trend**: The post-COVID section of the blue line is steeper than the pre-COVID section, suggesting that the rate of growth in GDP per capita after the initial pandemic shock may be faster than the growth rate before the pandemic.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer( ts, \n           type = \"text\", \n           dep.var.labels = (\"GDP Per Capita\"),\n           column.labels = (\"Model results\"),\n           covariate.labels = c(\"Time\", \"Treatment\", \"Time Since Treatment\"),\n           omit.stat = \"all\", \n           digits = 2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================\n                         Dependent variable:    \n                     ---------------------------\n                           GDP Per Capita       \n                            Model results       \n------------------------------------------------\nTime                          224.26***         \n                               (23.05)          \n                                                \nTreatment                   -5,566.75***        \n                              (438.41)          \n                                                \nTime Since Treatment          306.49***         \n                               (29.61)          \n                                                \nConstant                    19,112.23***        \n                              (182.95)          \n                                                \n================================================\n================================================\nNote:                *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\n\nThe interrupted regression result presented describes the impact of the onset of the COVID-19 pandemic on GDP per capita over time. Here's a detailed breakdown of the model's components and the statistical outputs:\n\n- **Time (`Ts`)**: The coefficient of 224.26 (with a standard error of 23.05) and significance indicated by three asterisks (`***`), suggesting a p-value less than 0.01, indicates that for every unit increase in time, the GDP per capita increases by approximately 224.26 units, assuming no treatment and not considering the passage of time since the treatment. This shows a general trend of GDP growth over time under normal circumstances.\n   \n- **Treatment (`D`)**: The treatment effect is -5,566.75 (with a standard error of 438.41), also highly significant (`***`). This suggests that the introduction of the treatment (the onset of the pandemic) leads to an immediate drop in GDP per capita by approximately 5,566.75 units. This captures the initial shock of the event on the economy.\n\n- **Time Since Treatment (`P`)**: The coefficient of 306.49 (with a standard error of 29.61) and significance (`***`), indicates that for each unit of time after the treatment, GDP per capita increases by about 306.49 units. This represents a recovery trajectory where, after the initial shock, GDP per capita begins to recover at this rate.\n\nIn summary, the model indicates that while the treatment had a significant negative impact on GDP per capita, there has been a subsequent positive rate of recovery over time following the initial shock. This provides a quantified insight into the economic impact of the event and its aftermath.\n\n## 1.2 Stock Price\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set options to suppress warnings\noptions(\"getSymbols.warning4.0\" = FALSE)\noptions(\"getSymbols.yahoo.warning\" = FALSE)\n\n# Define the tickers\ntickers <- c(\"PFE\")\n\n# Loop through tickers to get stock data\nfor (ticker in tickers) {\n  getSymbols(ticker,\n             from = \"2016-01-01\",\n             to = \"2024-01-01\")\n}\n\n# Create a data frame with adjusted closing prices\nstock <- data.frame(date = index(PFE), value = Ad(PFE))\n\n# data glimpse\nhead(stock, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 date PFE.Adjusted\n2016-01-04 2016-01-04     22.07899\n2016-01-05 2016-01-05     22.23794\n2016-01-06 2016-01-06     21.84404\n```\n:::\n\n```{.r .cell-code}\nfig <- plot_ly(stock, x = ~date, y = ~PFE.Adjusted,name = 'Pfizer Stock Price', type = 'scatter', mode = 'lines')\n\nfig\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-1c3d2b0dc4769d72f22a\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1c3d2b0dc4769d72f22a\">{\"x\":{\"visdat\":{\"cd6224b45296\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"cd6224b45296\",\"attrs\":{\"cd6224b45296\":{\"x\":{},\"y\":{},\"mode\":\"lines\",\"name\":\"Pfizer Stock Price\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"date\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"PFE.Adjusted\"},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[\"2016-01-04\",\"2016-01-05\",\"2016-01-06\",\"2016-01-07\",\"2016-01-08\",\"2016-01-11\",\"2016-01-12\",\"2016-01-13\",\"2016-01-14\",\"2016-01-15\",\"2016-01-19\",\"2016-01-20\",\"2016-01-21\",\"2016-01-22\",\"2016-01-25\",\"2016-01-26\",\"2016-01-27\",\"2016-01-28\",\"2016-01-29\",\"2016-02-01\",\"2016-02-02\",\"2016-02-03\",\"2016-02-04\",\"2016-02-05\",\"2016-02-08\",\"2016-02-09\",\"2016-02-10\",\"2016-02-11\",\"2016-02-12\",\"2016-02-16\",\"2016-02-17\",\"2016-02-18\",\"2016-02-19\",\"2016-02-22\",\"2016-02-23\",\"2016-02-24\",\"2016-02-25\",\"2016-02-26\",\"2016-02-29\",\"2016-03-01\",\"2016-03-02\",\"2016-03-03\",\"2016-03-04\",\"2016-03-07\",\"2016-03-08\",\"2016-03-09\",\"2016-03-10\",\"2016-03-11\",\"2016-03-14\",\"2016-03-15\",\"2016-03-16\",\"2016-03-17\",\"2016-03-18\",\"2016-03-21\",\"2016-03-22\",\"2016-03-23\",\"2016-03-24\",\"2016-03-28\",\"2016-03-29\",\"2016-03-30\",\"2016-03-31\",\"2016-04-01\",\"2016-04-04\",\"2016-04-05\",\"2016-04-06\",\"2016-04-07\",\"2016-04-08\",\"2016-04-11\",\"2016-04-12\",\"2016-04-13\",\"2016-04-14\",\"2016-04-15\",\"2016-04-18\",\"2016-04-19\",\"2016-04-20\",\"2016-04-21\",\"2016-04-22\",\"2016-04-25\",\"2016-04-26\",\"2016-04-27\",\"2016-04-28\",\"2016-04-29\",\"2016-05-02\",\"2016-05-03\",\"2016-05-04\",\"2016-05-05\",\"2016-05-06\",\"2016-05-09\",\"2016-05-10\",\"2016-05-11\",\"2016-05-12\",\"2016-05-13\",\"2016-05-16\",\"2016-05-17\",\"2016-05-18\",\"2016-05-19\",\"2016-05-20\",\"2016-05-23\",\"2016-05-24\",\"2016-05-25\",\"2016-05-26\",\"2016-05-27\",\"2016-05-31\",\"2016-06-01\",\"2016-06-02\",\"2016-06-03\",\"2016-06-06\",\"2016-06-07\",\"2016-06-08\",\"2016-06-09\",\"2016-06-10\",\"2016-06-13\",\"2016-06-14\",\"2016-06-15\",\"2016-06-16\",\"2016-06-17\",\"2016-06-20\",\"2016-06-21\",\"2016-06-22\",\"2016-06-23\",\"2016-06-24\",\"2016-06-27\",\"2016-06-28\",\"2016-06-29\",\"2016-06-30\",\"2016-07-01\",\"2016-07-05\",\"2016-07-06\",\"2016-07-07\",\"2016-07-08\",\"2016-07-11\",\"2016-07-12\",\"2016-07-13\",\"2016-07-14\",\"2016-07-15\",\"2016-07-18\",\"2016-07-19\",\"2016-07-20\",\"2016-07-21\",\"2016-07-22\",\"2016-07-25\",\"2016-07-26\",\"2016-07-27\",\"2016-07-28\",\"2016-07-29\",\"2016-08-01\",\"2016-08-02\",\"2016-08-03\",\"2016-08-04\",\"2016-08-05\",\"2016-08-08\",\"2016-08-09\",\"2016-08-10\",\"2016-08-11\",\"2016-08-12\",\"2016-08-15\",\"2016-08-16\",\"2016-08-17\",\"2016-08-18\",\"2016-08-19\",\"2016-08-22\",\"2016-08-23\",\"2016-08-24\",\"2016-08-25\",\"2016-08-26\",\"2016-08-29\",\"2016-08-30\",\"2016-08-31\",\"2016-09-01\",\"2016-09-02\",\"2016-09-06\",\"2016-09-07\",\"2016-09-08\",\"2016-09-09\",\"2016-09-12\",\"2016-09-13\",\"2016-09-14\",\"2016-09-15\",\"2016-09-16\",\"2016-09-19\",\"2016-09-20\",\"2016-09-21\",\"2016-09-22\",\"2016-09-23\",\"2016-09-26\",\"2016-09-27\",\"2016-09-28\",\"2016-09-29\",\"2016-09-30\",\"2016-10-03\",\"2016-10-04\",\"2016-10-05\",\"2016-10-06\",\"2016-10-07\",\"2016-10-10\",\"2016-10-11\",\"2016-10-12\",\"2016-10-13\",\"2016-10-14\",\"2016-10-17\",\"2016-10-18\",\"2016-10-19\",\"2016-10-20\",\"2016-10-21\",\"2016-10-24\",\"2016-10-25\",\"2016-10-26\",\"2016-10-27\",\"2016-10-28\",\"2016-10-31\",\"2016-11-01\",\"2016-11-02\",\"2016-11-03\",\"2016-11-04\",\"2016-11-07\",\"2016-11-08\",\"2016-11-09\",\"2016-11-10\",\"2016-11-11\",\"2016-11-14\",\"2016-11-15\",\"2016-11-16\",\"2016-11-17\",\"2016-11-18\",\"2016-11-21\",\"2016-11-22\",\"2016-11-23\",\"2016-11-25\",\"2016-11-28\",\"2016-11-29\",\"2016-11-30\",\"2016-12-01\",\"2016-12-02\",\"2016-12-05\",\"2016-12-06\",\"2016-12-07\",\"2016-12-08\",\"2016-12-09\",\"2016-12-12\",\"2016-12-13\",\"2016-12-14\",\"2016-12-15\",\"2016-12-16\",\"2016-12-19\",\"2016-12-20\",\"2016-12-21\",\"2016-12-22\",\"2016-12-23\",\"2016-12-27\",\"2016-12-28\",\"2016-12-29\",\"2016-12-30\",\"2017-01-03\",\"2017-01-04\",\"2017-01-05\",\"2017-01-06\",\"2017-01-09\",\"2017-01-10\",\"2017-01-11\",\"2017-01-12\",\"2017-01-13\",\"2017-01-17\",\"2017-01-18\",\"2017-01-19\",\"2017-01-20\",\"2017-01-23\",\"2017-01-24\",\"2017-01-25\",\"2017-01-26\",\"2017-01-27\",\"2017-01-30\",\"2017-01-31\",\"2017-02-01\",\"2017-02-02\",\"2017-02-03\",\"2017-02-06\",\"2017-02-07\",\"2017-02-08\",\"2017-02-09\",\"2017-02-10\",\"2017-02-13\",\"2017-02-14\",\"2017-02-15\",\"2017-02-16\",\"2017-02-17\",\"2017-02-21\",\"2017-02-22\",\"2017-02-23\",\"2017-02-24\",\"2017-02-27\",\"2017-02-28\",\"2017-03-01\",\"2017-03-02\",\"2017-03-03\",\"2017-03-06\",\"2017-03-07\",\"2017-03-08\",\"2017-03-09\",\"2017-03-10\",\"2017-03-13\",\"2017-03-14\",\"2017-03-15\",\"2017-03-16\",\"2017-03-17\",\"2017-03-20\",\"2017-03-21\",\"2017-03-22\",\"2017-03-23\",\"2017-03-24\",\"2017-03-27\",\"2017-03-28\",\"2017-03-29\",\"2017-03-30\",\"2017-03-31\",\"2017-04-03\",\"2017-04-04\",\"2017-04-05\",\"2017-04-06\",\"2017-04-07\",\"2017-04-10\",\"2017-04-11\",\"2017-04-12\",\"2017-04-13\",\"2017-04-17\",\"2017-04-18\",\"2017-04-19\",\"2017-04-20\",\"2017-04-21\",\"2017-04-24\",\"2017-04-25\",\"2017-04-26\",\"2017-04-27\",\"2017-04-28\",\"2017-05-01\",\"2017-05-02\",\"2017-05-03\",\"2017-05-04\",\"2017-05-05\",\"2017-05-08\",\"2017-05-09\",\"2017-05-10\",\"2017-05-11\",\"2017-05-12\",\"2017-05-15\",\"2017-05-16\",\"2017-05-17\",\"2017-05-18\",\"2017-05-19\",\"2017-05-22\",\"2017-05-23\",\"2017-05-24\",\"2017-05-25\",\"2017-05-26\",\"2017-05-30\",\"2017-05-31\",\"2017-06-01\",\"2017-06-02\",\"2017-06-05\",\"2017-06-06\",\"2017-06-07\",\"2017-06-08\",\"2017-06-09\",\"2017-06-12\",\"2017-06-13\",\"2017-06-14\",\"2017-06-15\",\"2017-06-16\",\"2017-06-19\",\"2017-06-20\",\"2017-06-21\",\"2017-06-22\",\"2017-06-23\",\"2017-06-26\",\"2017-06-27\",\"2017-06-28\",\"2017-06-29\",\"2017-06-30\",\"2017-07-03\",\"2017-07-05\",\"2017-07-06\",\"2017-07-07\",\"2017-07-10\",\"2017-07-11\",\"2017-07-12\",\"2017-07-13\",\"2017-07-14\",\"2017-07-17\",\"2017-07-18\",\"2017-07-19\",\"2017-07-20\",\"2017-07-21\",\"2017-07-24\",\"2017-07-25\",\"2017-07-26\",\"2017-07-27\",\"2017-07-28\",\"2017-07-31\",\"2017-08-01\",\"2017-08-02\",\"2017-08-03\",\"2017-08-04\",\"2017-08-07\",\"2017-08-08\",\"2017-08-09\",\"2017-08-10\",\"2017-08-11\",\"2017-08-14\",\"2017-08-15\",\"2017-08-16\",\"2017-08-17\",\"2017-08-18\",\"2017-08-21\",\"2017-08-22\",\"2017-08-23\",\"2017-08-24\",\"2017-08-25\",\"2017-08-28\",\"2017-08-29\",\"2017-08-30\",\"2017-08-31\",\"2017-09-01\",\"2017-09-05\",\"2017-09-06\",\"2017-09-07\",\"2017-09-08\",\"2017-09-11\",\"2017-09-12\",\"2017-09-13\",\"2017-09-14\",\"2017-09-15\",\"2017-09-18\",\"2017-09-19\",\"2017-09-20\",\"2017-09-21\",\"2017-09-22\",\"2017-09-25\",\"2017-09-26\",\"2017-09-27\",\"2017-09-28\",\"2017-09-29\",\"2017-10-02\",\"2017-10-03\",\"2017-10-04\",\"2017-10-05\",\"2017-10-06\",\"2017-10-09\",\"2017-10-10\",\"2017-10-11\",\"2017-10-12\",\"2017-10-13\",\"2017-10-16\",\"2017-10-17\",\"2017-10-18\",\"2017-10-19\",\"2017-10-20\",\"2017-10-23\",\"2017-10-24\",\"2017-10-25\",\"2017-10-26\",\"2017-10-27\",\"2017-10-30\",\"2017-10-31\",\"2017-11-01\",\"2017-11-02\",\"2017-11-03\",\"2017-11-06\",\"2017-11-07\",\"2017-11-08\",\"2017-11-09\",\"2017-11-10\",\"2017-11-13\",\"2017-11-14\",\"2017-11-15\",\"2017-11-16\",\"2017-11-17\",\"2017-11-20\",\"2017-11-21\",\"2017-11-22\",\"2017-11-24\",\"2017-11-27\",\"2017-11-28\",\"2017-11-29\",\"2017-11-30\",\"2017-12-01\",\"2017-12-04\",\"2017-12-05\",\"2017-12-06\",\"2017-12-07\",\"2017-12-08\",\"2017-12-11\",\"2017-12-12\",\"2017-12-13\",\"2017-12-14\",\"2017-12-15\",\"2017-12-18\",\"2017-12-19\",\"2017-12-20\",\"2017-12-21\",\"2017-12-22\",\"2017-12-26\",\"2017-12-27\",\"2017-12-28\",\"2017-12-29\",\"2018-01-02\",\"2018-01-03\",\"2018-01-04\",\"2018-01-05\",\"2018-01-08\",\"2018-01-09\",\"2018-01-10\",\"2018-01-11\",\"2018-01-12\",\"2018-01-16\",\"2018-01-17\",\"2018-01-18\",\"2018-01-19\",\"2018-01-22\",\"2018-01-23\",\"2018-01-24\",\"2018-01-25\",\"2018-01-26\",\"2018-01-29\",\"2018-01-30\",\"2018-01-31\",\"2018-02-01\",\"2018-02-02\",\"2018-02-05\",\"2018-02-06\",\"2018-02-07\",\"2018-02-08\",\"2018-02-09\",\"2018-02-12\",\"2018-02-13\",\"2018-02-14\",\"2018-02-15\",\"2018-02-16\",\"2018-02-20\",\"2018-02-21\",\"2018-02-22\",\"2018-02-23\",\"2018-02-26\",\"2018-02-27\",\"2018-02-28\",\"2018-03-01\",\"2018-03-02\",\"2018-03-05\",\"2018-03-06\",\"2018-03-07\",\"2018-03-08\",\"2018-03-09\",\"2018-03-12\",\"2018-03-13\",\"2018-03-14\",\"2018-03-15\",\"2018-03-16\",\"2018-03-19\",\"2018-03-20\",\"2018-03-21\",\"2018-03-22\",\"2018-03-23\",\"2018-03-26\",\"2018-03-27\",\"2018-03-28\",\"2018-03-29\",\"2018-04-02\",\"2018-04-03\",\"2018-04-04\",\"2018-04-05\",\"2018-04-06\",\"2018-04-09\",\"2018-04-10\",\"2018-04-11\",\"2018-04-12\",\"2018-04-13\",\"2018-04-16\",\"2018-04-17\",\"2018-04-18\",\"2018-04-19\",\"2018-04-20\",\"2018-04-23\",\"2018-04-24\",\"2018-04-25\",\"2018-04-26\",\"2018-04-27\",\"2018-04-30\",\"2018-05-01\",\"2018-05-02\",\"2018-05-03\",\"2018-05-04\",\"2018-05-07\",\"2018-05-08\",\"2018-05-09\",\"2018-05-10\",\"2018-05-11\",\"2018-05-14\",\"2018-05-15\",\"2018-05-16\",\"2018-05-17\",\"2018-05-18\",\"2018-05-21\",\"2018-05-22\",\"2018-05-23\",\"2018-05-24\",\"2018-05-25\",\"2018-05-29\",\"2018-05-30\",\"2018-05-31\",\"2018-06-01\",\"2018-06-04\",\"2018-06-05\",\"2018-06-06\",\"2018-06-07\",\"2018-06-08\",\"2018-06-11\",\"2018-06-12\",\"2018-06-13\",\"2018-06-14\",\"2018-06-15\",\"2018-06-18\",\"2018-06-19\",\"2018-06-20\",\"2018-06-21\",\"2018-06-22\",\"2018-06-25\",\"2018-06-26\",\"2018-06-27\",\"2018-06-28\",\"2018-06-29\",\"2018-07-02\",\"2018-07-03\",\"2018-07-05\",\"2018-07-06\",\"2018-07-09\",\"2018-07-10\",\"2018-07-11\",\"2018-07-12\",\"2018-07-13\",\"2018-07-16\",\"2018-07-17\",\"2018-07-18\",\"2018-07-19\",\"2018-07-20\",\"2018-07-23\",\"2018-07-24\",\"2018-07-25\",\"2018-07-26\",\"2018-07-27\",\"2018-07-30\",\"2018-07-31\",\"2018-08-01\",\"2018-08-02\",\"2018-08-03\",\"2018-08-06\",\"2018-08-07\",\"2018-08-08\",\"2018-08-09\",\"2018-08-10\",\"2018-08-13\",\"2018-08-14\",\"2018-08-15\",\"2018-08-16\",\"2018-08-17\",\"2018-08-20\",\"2018-08-21\",\"2018-08-22\",\"2018-08-23\",\"2018-08-24\",\"2018-08-27\",\"2018-08-28\",\"2018-08-29\",\"2018-08-30\",\"2018-08-31\",\"2018-09-04\",\"2018-09-05\",\"2018-09-06\",\"2018-09-07\",\"2018-09-10\",\"2018-09-11\",\"2018-09-12\",\"2018-09-13\",\"2018-09-14\",\"2018-09-17\",\"2018-09-18\",\"2018-09-19\",\"2018-09-20\",\"2018-09-21\",\"2018-09-24\",\"2018-09-25\",\"2018-09-26\",\"2018-09-27\",\"2018-09-28\",\"2018-10-01\",\"2018-10-02\",\"2018-10-03\",\"2018-10-04\",\"2018-10-05\",\"2018-10-08\",\"2018-10-09\",\"2018-10-10\",\"2018-10-11\",\"2018-10-12\",\"2018-10-15\",\"2018-10-16\",\"2018-10-17\",\"2018-10-18\",\"2018-10-19\",\"2018-10-22\",\"2018-10-23\",\"2018-10-24\",\"2018-10-25\",\"2018-10-26\",\"2018-10-29\",\"2018-10-30\",\"2018-10-31\",\"2018-11-01\",\"2018-11-02\",\"2018-11-05\",\"2018-11-06\",\"2018-11-07\",\"2018-11-08\",\"2018-11-09\",\"2018-11-12\",\"2018-11-13\",\"2018-11-14\",\"2018-11-15\",\"2018-11-16\",\"2018-11-19\",\"2018-11-20\",\"2018-11-21\",\"2018-11-23\",\"2018-11-26\",\"2018-11-27\",\"2018-11-28\",\"2018-11-29\",\"2018-11-30\",\"2018-12-03\",\"2018-12-04\",\"2018-12-06\",\"2018-12-07\",\"2018-12-10\",\"2018-12-11\",\"2018-12-12\",\"2018-12-13\",\"2018-12-14\",\"2018-12-17\",\"2018-12-18\",\"2018-12-19\",\"2018-12-20\",\"2018-12-21\",\"2018-12-24\",\"2018-12-26\",\"2018-12-27\",\"2018-12-28\",\"2018-12-31\",\"2019-01-02\",\"2019-01-03\",\"2019-01-04\",\"2019-01-07\",\"2019-01-08\",\"2019-01-09\",\"2019-01-10\",\"2019-01-11\",\"2019-01-14\",\"2019-01-15\",\"2019-01-16\",\"2019-01-17\",\"2019-01-18\",\"2019-01-22\",\"2019-01-23\",\"2019-01-24\",\"2019-01-25\",\"2019-01-28\",\"2019-01-29\",\"2019-01-30\",\"2019-01-31\",\"2019-02-01\",\"2019-02-04\",\"2019-02-05\",\"2019-02-06\",\"2019-02-07\",\"2019-02-08\",\"2019-02-11\",\"2019-02-12\",\"2019-02-13\",\"2019-02-14\",\"2019-02-15\",\"2019-02-19\",\"2019-02-20\",\"2019-02-21\",\"2019-02-22\",\"2019-02-25\",\"2019-02-26\",\"2019-02-27\",\"2019-02-28\",\"2019-03-01\",\"2019-03-04\",\"2019-03-05\",\"2019-03-06\",\"2019-03-07\",\"2019-03-08\",\"2019-03-11\",\"2019-03-12\",\"2019-03-13\",\"2019-03-14\",\"2019-03-15\",\"2019-03-18\",\"2019-03-19\",\"2019-03-20\",\"2019-03-21\",\"2019-03-22\",\"2019-03-25\",\"2019-03-26\",\"2019-03-27\",\"2019-03-28\",\"2019-03-29\",\"2019-04-01\",\"2019-04-02\",\"2019-04-03\",\"2019-04-04\",\"2019-04-05\",\"2019-04-08\",\"2019-04-09\",\"2019-04-10\",\"2019-04-11\",\"2019-04-12\",\"2019-04-15\",\"2019-04-16\",\"2019-04-17\",\"2019-04-18\",\"2019-04-22\",\"2019-04-23\",\"2019-04-24\",\"2019-04-25\",\"2019-04-26\",\"2019-04-29\",\"2019-04-30\",\"2019-05-01\",\"2019-05-02\",\"2019-05-03\",\"2019-05-06\",\"2019-05-07\",\"2019-05-08\",\"2019-05-09\",\"2019-05-10\",\"2019-05-13\",\"2019-05-14\",\"2019-05-15\",\"2019-05-16\",\"2019-05-17\",\"2019-05-20\",\"2019-05-21\",\"2019-05-22\",\"2019-05-23\",\"2019-05-24\",\"2019-05-28\",\"2019-05-29\",\"2019-05-30\",\"2019-05-31\",\"2019-06-03\",\"2019-06-04\",\"2019-06-05\",\"2019-06-06\",\"2019-06-07\",\"2019-06-10\",\"2019-06-11\",\"2019-06-12\",\"2019-06-13\",\"2019-06-14\",\"2019-06-17\",\"2019-06-18\",\"2019-06-19\",\"2019-06-20\",\"2019-06-21\",\"2019-06-24\",\"2019-06-25\",\"2019-06-26\",\"2019-06-27\",\"2019-06-28\",\"2019-07-01\",\"2019-07-02\",\"2019-07-03\",\"2019-07-05\",\"2019-07-08\",\"2019-07-09\",\"2019-07-10\",\"2019-07-11\",\"2019-07-12\",\"2019-07-15\",\"2019-07-16\",\"2019-07-17\",\"2019-07-18\",\"2019-07-19\",\"2019-07-22\",\"2019-07-23\",\"2019-07-24\",\"2019-07-25\",\"2019-07-26\",\"2019-07-29\",\"2019-07-30\",\"2019-07-31\",\"2019-08-01\",\"2019-08-02\",\"2019-08-05\",\"2019-08-06\",\"2019-08-07\",\"2019-08-08\",\"2019-08-09\",\"2019-08-12\",\"2019-08-13\",\"2019-08-14\",\"2019-08-15\",\"2019-08-16\",\"2019-08-19\",\"2019-08-20\",\"2019-08-21\",\"2019-08-22\",\"2019-08-23\",\"2019-08-26\",\"2019-08-27\",\"2019-08-28\",\"2019-08-29\",\"2019-08-30\",\"2019-09-03\",\"2019-09-04\",\"2019-09-05\",\"2019-09-06\",\"2019-09-09\",\"2019-09-10\",\"2019-09-11\",\"2019-09-12\",\"2019-09-13\",\"2019-09-16\",\"2019-09-17\",\"2019-09-18\",\"2019-09-19\",\"2019-09-20\",\"2019-09-23\",\"2019-09-24\",\"2019-09-25\",\"2019-09-26\",\"2019-09-27\",\"2019-09-30\",\"2019-10-01\",\"2019-10-02\",\"2019-10-03\",\"2019-10-04\",\"2019-10-07\",\"2019-10-08\",\"2019-10-09\",\"2019-10-10\",\"2019-10-11\",\"2019-10-14\",\"2019-10-15\",\"2019-10-16\",\"2019-10-17\",\"2019-10-18\",\"2019-10-21\",\"2019-10-22\",\"2019-10-23\",\"2019-10-24\",\"2019-10-25\",\"2019-10-28\",\"2019-10-29\",\"2019-10-30\",\"2019-10-31\",\"2019-11-01\",\"2019-11-04\",\"2019-11-05\",\"2019-11-06\",\"2019-11-07\",\"2019-11-08\",\"2019-11-11\",\"2019-11-12\",\"2019-11-13\",\"2019-11-14\",\"2019-11-15\",\"2019-11-18\",\"2019-11-19\",\"2019-11-20\",\"2019-11-21\",\"2019-11-22\",\"2019-11-25\",\"2019-11-26\",\"2019-11-27\",\"2019-11-29\",\"2019-12-02\",\"2019-12-03\",\"2019-12-04\",\"2019-12-05\",\"2019-12-06\",\"2019-12-09\",\"2019-12-10\",\"2019-12-11\",\"2019-12-12\",\"2019-12-13\",\"2019-12-16\",\"2019-12-17\",\"2019-12-18\",\"2019-12-19\",\"2019-12-20\",\"2019-12-23\",\"2019-12-24\",\"2019-12-26\",\"2019-12-27\",\"2019-12-30\",\"2019-12-31\",\"2020-01-02\",\"2020-01-03\",\"2020-01-06\",\"2020-01-07\",\"2020-01-08\",\"2020-01-09\",\"2020-01-10\",\"2020-01-13\",\"2020-01-14\",\"2020-01-15\",\"2020-01-16\",\"2020-01-17\",\"2020-01-21\",\"2020-01-22\",\"2020-01-23\",\"2020-01-24\",\"2020-01-27\",\"2020-01-28\",\"2020-01-29\",\"2020-01-30\",\"2020-01-31\",\"2020-02-03\",\"2020-02-04\",\"2020-02-05\",\"2020-02-06\",\"2020-02-07\",\"2020-02-10\",\"2020-02-11\",\"2020-02-12\",\"2020-02-13\",\"2020-02-14\",\"2020-02-18\",\"2020-02-19\",\"2020-02-20\",\"2020-02-21\",\"2020-02-24\",\"2020-02-25\",\"2020-02-26\",\"2020-02-27\",\"2020-02-28\",\"2020-03-02\",\"2020-03-03\",\"2020-03-04\",\"2020-03-05\",\"2020-03-06\",\"2020-03-09\",\"2020-03-10\",\"2020-03-11\",\"2020-03-12\",\"2020-03-13\",\"2020-03-16\",\"2020-03-17\",\"2020-03-18\",\"2020-03-19\",\"2020-03-20\",\"2020-03-23\",\"2020-03-24\",\"2020-03-25\",\"2020-03-26\",\"2020-03-27\",\"2020-03-30\",\"2020-03-31\",\"2020-04-01\",\"2020-04-02\",\"2020-04-03\",\"2020-04-06\",\"2020-04-07\",\"2020-04-08\",\"2020-04-09\",\"2020-04-13\",\"2020-04-14\",\"2020-04-15\",\"2020-04-16\",\"2020-04-17\",\"2020-04-20\",\"2020-04-21\",\"2020-04-22\",\"2020-04-23\",\"2020-04-24\",\"2020-04-27\",\"2020-04-28\",\"2020-04-29\",\"2020-04-30\",\"2020-05-01\",\"2020-05-04\",\"2020-05-05\",\"2020-05-06\",\"2020-05-07\",\"2020-05-08\",\"2020-05-11\",\"2020-05-12\",\"2020-05-13\",\"2020-05-14\",\"2020-05-15\",\"2020-05-18\",\"2020-05-19\",\"2020-05-20\",\"2020-05-21\",\"2020-05-22\",\"2020-05-26\",\"2020-05-27\",\"2020-05-28\",\"2020-05-29\",\"2020-06-01\",\"2020-06-02\",\"2020-06-03\",\"2020-06-04\",\"2020-06-05\",\"2020-06-08\",\"2020-06-09\",\"2020-06-10\",\"2020-06-11\",\"2020-06-12\",\"2020-06-15\",\"2020-06-16\",\"2020-06-17\",\"2020-06-18\",\"2020-06-19\",\"2020-06-22\",\"2020-06-23\",\"2020-06-24\",\"2020-06-25\",\"2020-06-26\",\"2020-06-29\",\"2020-06-30\",\"2020-07-01\",\"2020-07-02\",\"2020-07-06\",\"2020-07-07\",\"2020-07-08\",\"2020-07-09\",\"2020-07-10\",\"2020-07-13\",\"2020-07-14\",\"2020-07-15\",\"2020-07-16\",\"2020-07-17\",\"2020-07-20\",\"2020-07-21\",\"2020-07-22\",\"2020-07-23\",\"2020-07-24\",\"2020-07-27\",\"2020-07-28\",\"2020-07-29\",\"2020-07-30\",\"2020-07-31\",\"2020-08-03\",\"2020-08-04\",\"2020-08-05\",\"2020-08-06\",\"2020-08-07\",\"2020-08-10\",\"2020-08-11\",\"2020-08-12\",\"2020-08-13\",\"2020-08-14\",\"2020-08-17\",\"2020-08-18\",\"2020-08-19\",\"2020-08-20\",\"2020-08-21\",\"2020-08-24\",\"2020-08-25\",\"2020-08-26\",\"2020-08-27\",\"2020-08-28\",\"2020-08-31\",\"2020-09-01\",\"2020-09-02\",\"2020-09-03\",\"2020-09-04\",\"2020-09-08\",\"2020-09-09\",\"2020-09-10\",\"2020-09-11\",\"2020-09-14\",\"2020-09-15\",\"2020-09-16\",\"2020-09-17\",\"2020-09-18\",\"2020-09-21\",\"2020-09-22\",\"2020-09-23\",\"2020-09-24\",\"2020-09-25\",\"2020-09-28\",\"2020-09-29\",\"2020-09-30\",\"2020-10-01\",\"2020-10-02\",\"2020-10-05\",\"2020-10-06\",\"2020-10-07\",\"2020-10-08\",\"2020-10-09\",\"2020-10-12\",\"2020-10-13\",\"2020-10-14\",\"2020-10-15\",\"2020-10-16\",\"2020-10-19\",\"2020-10-20\",\"2020-10-21\",\"2020-10-22\",\"2020-10-23\",\"2020-10-26\",\"2020-10-27\",\"2020-10-28\",\"2020-10-29\",\"2020-10-30\",\"2020-11-02\",\"2020-11-03\",\"2020-11-04\",\"2020-11-05\",\"2020-11-06\",\"2020-11-09\",\"2020-11-10\",\"2020-11-11\",\"2020-11-12\",\"2020-11-13\",\"2020-11-16\",\"2020-11-17\",\"2020-11-18\",\"2020-11-19\",\"2020-11-20\",\"2020-11-23\",\"2020-11-24\",\"2020-11-25\",\"2020-11-27\",\"2020-11-30\",\"2020-12-01\",\"2020-12-02\",\"2020-12-03\",\"2020-12-04\",\"2020-12-07\",\"2020-12-08\",\"2020-12-09\",\"2020-12-10\",\"2020-12-11\",\"2020-12-14\",\"2020-12-15\",\"2020-12-16\",\"2020-12-17\",\"2020-12-18\",\"2020-12-21\",\"2020-12-22\",\"2020-12-23\",\"2020-12-24\",\"2020-12-28\",\"2020-12-29\",\"2020-12-30\",\"2020-12-31\",\"2021-01-04\",\"2021-01-05\",\"2021-01-06\",\"2021-01-07\",\"2021-01-08\",\"2021-01-11\",\"2021-01-12\",\"2021-01-13\",\"2021-01-14\",\"2021-01-15\",\"2021-01-19\",\"2021-01-20\",\"2021-01-21\",\"2021-01-22\",\"2021-01-25\",\"2021-01-26\",\"2021-01-27\",\"2021-01-28\",\"2021-01-29\",\"2021-02-01\",\"2021-02-02\",\"2021-02-03\",\"2021-02-04\",\"2021-02-05\",\"2021-02-08\",\"2021-02-09\",\"2021-02-10\",\"2021-02-11\",\"2021-02-12\",\"2021-02-16\",\"2021-02-17\",\"2021-02-18\",\"2021-02-19\",\"2021-02-22\",\"2021-02-23\",\"2021-02-24\",\"2021-02-25\",\"2021-02-26\",\"2021-03-01\",\"2021-03-02\",\"2021-03-03\",\"2021-03-04\",\"2021-03-05\",\"2021-03-08\",\"2021-03-09\",\"2021-03-10\",\"2021-03-11\",\"2021-03-12\",\"2021-03-15\",\"2021-03-16\",\"2021-03-17\",\"2021-03-18\",\"2021-03-19\",\"2021-03-22\",\"2021-03-23\",\"2021-03-24\",\"2021-03-25\",\"2021-03-26\",\"2021-03-29\",\"2021-03-30\",\"2021-03-31\",\"2021-04-01\",\"2021-04-05\",\"2021-04-06\",\"2021-04-07\",\"2021-04-08\",\"2021-04-09\",\"2021-04-12\",\"2021-04-13\",\"2021-04-14\",\"2021-04-15\",\"2021-04-16\",\"2021-04-19\",\"2021-04-20\",\"2021-04-21\",\"2021-04-22\",\"2021-04-23\",\"2021-04-26\",\"2021-04-27\",\"2021-04-28\",\"2021-04-29\",\"2021-04-30\",\"2021-05-03\",\"2021-05-04\",\"2021-05-05\",\"2021-05-06\",\"2021-05-07\",\"2021-05-10\",\"2021-05-11\",\"2021-05-12\",\"2021-05-13\",\"2021-05-14\",\"2021-05-17\",\"2021-05-18\",\"2021-05-19\",\"2021-05-20\",\"2021-05-21\",\"2021-05-24\",\"2021-05-25\",\"2021-05-26\",\"2021-05-27\",\"2021-05-28\",\"2021-06-01\",\"2021-06-02\",\"2021-06-03\",\"2021-06-04\",\"2021-06-07\",\"2021-06-08\",\"2021-06-09\",\"2021-06-10\",\"2021-06-11\",\"2021-06-14\",\"2021-06-15\",\"2021-06-16\",\"2021-06-17\",\"2021-06-18\",\"2021-06-21\",\"2021-06-22\",\"2021-06-23\",\"2021-06-24\",\"2021-06-25\",\"2021-06-28\",\"2021-06-29\",\"2021-06-30\",\"2021-07-01\",\"2021-07-02\",\"2021-07-06\",\"2021-07-07\",\"2021-07-08\",\"2021-07-09\",\"2021-07-12\",\"2021-07-13\",\"2021-07-14\",\"2021-07-15\",\"2021-07-16\",\"2021-07-19\",\"2021-07-20\",\"2021-07-21\",\"2021-07-22\",\"2021-07-23\",\"2021-07-26\",\"2021-07-27\",\"2021-07-28\",\"2021-07-29\",\"2021-07-30\",\"2021-08-02\",\"2021-08-03\",\"2021-08-04\",\"2021-08-05\",\"2021-08-06\",\"2021-08-09\",\"2021-08-10\",\"2021-08-11\",\"2021-08-12\",\"2021-08-13\",\"2021-08-16\",\"2021-08-17\",\"2021-08-18\",\"2021-08-19\",\"2021-08-20\",\"2021-08-23\",\"2021-08-24\",\"2021-08-25\",\"2021-08-26\",\"2021-08-27\",\"2021-08-30\",\"2021-08-31\",\"2021-09-01\",\"2021-09-02\",\"2021-09-03\",\"2021-09-07\",\"2021-09-08\",\"2021-09-09\",\"2021-09-10\",\"2021-09-13\",\"2021-09-14\",\"2021-09-15\",\"2021-09-16\",\"2021-09-17\",\"2021-09-20\",\"2021-09-21\",\"2021-09-22\",\"2021-09-23\",\"2021-09-24\",\"2021-09-27\",\"2021-09-28\",\"2021-09-29\",\"2021-09-30\",\"2021-10-01\",\"2021-10-04\",\"2021-10-05\",\"2021-10-06\",\"2021-10-07\",\"2021-10-08\",\"2021-10-11\",\"2021-10-12\",\"2021-10-13\",\"2021-10-14\",\"2021-10-15\",\"2021-10-18\",\"2021-10-19\",\"2021-10-20\",\"2021-10-21\",\"2021-10-22\",\"2021-10-25\",\"2021-10-26\",\"2021-10-27\",\"2021-10-28\",\"2021-10-29\",\"2021-11-01\",\"2021-11-02\",\"2021-11-03\",\"2021-11-04\",\"2021-11-05\",\"2021-11-08\",\"2021-11-09\",\"2021-11-10\",\"2021-11-11\",\"2021-11-12\",\"2021-11-15\",\"2021-11-16\",\"2021-11-17\",\"2021-11-18\",\"2021-11-19\",\"2021-11-22\",\"2021-11-23\",\"2021-11-24\",\"2021-11-26\",\"2021-11-29\",\"2021-11-30\",\"2021-12-01\",\"2021-12-02\",\"2021-12-03\",\"2021-12-06\",\"2021-12-07\",\"2021-12-08\",\"2021-12-09\",\"2021-12-10\",\"2021-12-13\",\"2021-12-14\",\"2021-12-15\",\"2021-12-16\",\"2021-12-17\",\"2021-12-20\",\"2021-12-21\",\"2021-12-22\",\"2021-12-23\",\"2021-12-27\",\"2021-12-28\",\"2021-12-29\",\"2021-12-30\",\"2021-12-31\",\"2022-01-03\",\"2022-01-04\",\"2022-01-05\",\"2022-01-06\",\"2022-01-07\",\"2022-01-10\",\"2022-01-11\",\"2022-01-12\",\"2022-01-13\",\"2022-01-14\",\"2022-01-18\",\"2022-01-19\",\"2022-01-20\",\"2022-01-21\",\"2022-01-24\",\"2022-01-25\",\"2022-01-26\",\"2022-01-27\",\"2022-01-28\",\"2022-01-31\",\"2022-02-01\",\"2022-02-02\",\"2022-02-03\",\"2022-02-04\",\"2022-02-07\",\"2022-02-08\",\"2022-02-09\",\"2022-02-10\",\"2022-02-11\",\"2022-02-14\",\"2022-02-15\",\"2022-02-16\",\"2022-02-17\",\"2022-02-18\",\"2022-02-22\",\"2022-02-23\",\"2022-02-24\",\"2022-02-25\",\"2022-02-28\",\"2022-03-01\",\"2022-03-02\",\"2022-03-03\",\"2022-03-04\",\"2022-03-07\",\"2022-03-08\",\"2022-03-09\",\"2022-03-10\",\"2022-03-11\",\"2022-03-14\",\"2022-03-15\",\"2022-03-16\",\"2022-03-17\",\"2022-03-18\",\"2022-03-21\",\"2022-03-22\",\"2022-03-23\",\"2022-03-24\",\"2022-03-25\",\"2022-03-28\",\"2022-03-29\",\"2022-03-30\",\"2022-03-31\",\"2022-04-01\",\"2022-04-04\",\"2022-04-05\",\"2022-04-06\",\"2022-04-07\",\"2022-04-08\",\"2022-04-11\",\"2022-04-12\",\"2022-04-13\",\"2022-04-14\",\"2022-04-18\",\"2022-04-19\",\"2022-04-20\",\"2022-04-21\",\"2022-04-22\",\"2022-04-25\",\"2022-04-26\",\"2022-04-27\",\"2022-04-28\",\"2022-04-29\",\"2022-05-02\",\"2022-05-03\",\"2022-05-04\",\"2022-05-05\",\"2022-05-06\",\"2022-05-09\",\"2022-05-10\",\"2022-05-11\",\"2022-05-12\",\"2022-05-13\",\"2022-05-16\",\"2022-05-17\",\"2022-05-18\",\"2022-05-19\",\"2022-05-20\",\"2022-05-23\",\"2022-05-24\",\"2022-05-25\",\"2022-05-26\",\"2022-05-27\",\"2022-05-31\",\"2022-06-01\",\"2022-06-02\",\"2022-06-03\",\"2022-06-06\",\"2022-06-07\",\"2022-06-08\",\"2022-06-09\",\"2022-06-10\",\"2022-06-13\",\"2022-06-14\",\"2022-06-15\",\"2022-06-16\",\"2022-06-17\",\"2022-06-21\",\"2022-06-22\",\"2022-06-23\",\"2022-06-24\",\"2022-06-27\",\"2022-06-28\",\"2022-06-29\",\"2022-06-30\",\"2022-07-01\",\"2022-07-05\",\"2022-07-06\",\"2022-07-07\",\"2022-07-08\",\"2022-07-11\",\"2022-07-12\",\"2022-07-13\",\"2022-07-14\",\"2022-07-15\",\"2022-07-18\",\"2022-07-19\",\"2022-07-20\",\"2022-07-21\",\"2022-07-22\",\"2022-07-25\",\"2022-07-26\",\"2022-07-27\",\"2022-07-28\",\"2022-07-29\",\"2022-08-01\",\"2022-08-02\",\"2022-08-03\",\"2022-08-04\",\"2022-08-05\",\"2022-08-08\",\"2022-08-09\",\"2022-08-10\",\"2022-08-11\",\"2022-08-12\",\"2022-08-15\",\"2022-08-16\",\"2022-08-17\",\"2022-08-18\",\"2022-08-19\",\"2022-08-22\",\"2022-08-23\",\"2022-08-24\",\"2022-08-25\",\"2022-08-26\",\"2022-08-29\",\"2022-08-30\",\"2022-08-31\",\"2022-09-01\",\"2022-09-02\",\"2022-09-06\",\"2022-09-07\",\"2022-09-08\",\"2022-09-09\",\"2022-09-12\",\"2022-09-13\",\"2022-09-14\",\"2022-09-15\",\"2022-09-16\",\"2022-09-19\",\"2022-09-20\",\"2022-09-21\",\"2022-09-22\",\"2022-09-23\",\"2022-09-26\",\"2022-09-27\",\"2022-09-28\",\"2022-09-29\",\"2022-09-30\",\"2022-10-03\",\"2022-10-04\",\"2022-10-05\",\"2022-10-06\",\"2022-10-07\",\"2022-10-10\",\"2022-10-11\",\"2022-10-12\",\"2022-10-13\",\"2022-10-14\",\"2022-10-17\",\"2022-10-18\",\"2022-10-19\",\"2022-10-20\",\"2022-10-21\",\"2022-10-24\",\"2022-10-25\",\"2022-10-26\",\"2022-10-27\",\"2022-10-28\",\"2022-10-31\",\"2022-11-01\",\"2022-11-02\",\"2022-11-03\",\"2022-11-04\",\"2022-11-07\",\"2022-11-08\",\"2022-11-09\",\"2022-11-10\",\"2022-11-11\",\"2022-11-14\",\"2022-11-15\",\"2022-11-16\",\"2022-11-17\",\"2022-11-18\",\"2022-11-21\",\"2022-11-22\",\"2022-11-23\",\"2022-11-25\",\"2022-11-28\",\"2022-11-29\",\"2022-11-30\",\"2022-12-01\",\"2022-12-02\",\"2022-12-05\",\"2022-12-06\",\"2022-12-07\",\"2022-12-08\",\"2022-12-09\",\"2022-12-12\",\"2022-12-13\",\"2022-12-14\",\"2022-12-15\",\"2022-12-16\",\"2022-12-19\",\"2022-12-20\",\"2022-12-21\",\"2022-12-22\",\"2022-12-23\",\"2022-12-27\",\"2022-12-28\",\"2022-12-29\",\"2022-12-30\",\"2023-01-03\",\"2023-01-04\",\"2023-01-05\",\"2023-01-06\",\"2023-01-09\",\"2023-01-10\",\"2023-01-11\",\"2023-01-12\",\"2023-01-13\",\"2023-01-17\",\"2023-01-18\",\"2023-01-19\",\"2023-01-20\",\"2023-01-23\",\"2023-01-24\",\"2023-01-25\",\"2023-01-26\",\"2023-01-27\",\"2023-01-30\",\"2023-01-31\",\"2023-02-01\",\"2023-02-02\",\"2023-02-03\",\"2023-02-06\",\"2023-02-07\",\"2023-02-08\",\"2023-02-09\",\"2023-02-10\",\"2023-02-13\",\"2023-02-14\",\"2023-02-15\",\"2023-02-16\",\"2023-02-17\",\"2023-02-21\",\"2023-02-22\",\"2023-02-23\",\"2023-02-24\",\"2023-02-27\",\"2023-02-28\",\"2023-03-01\",\"2023-03-02\",\"2023-03-03\",\"2023-03-06\",\"2023-03-07\",\"2023-03-08\",\"2023-03-09\",\"2023-03-10\",\"2023-03-13\",\"2023-03-14\",\"2023-03-15\",\"2023-03-16\",\"2023-03-17\",\"2023-03-20\",\"2023-03-21\",\"2023-03-22\",\"2023-03-23\",\"2023-03-24\",\"2023-03-27\",\"2023-03-28\",\"2023-03-29\",\"2023-03-30\",\"2023-03-31\",\"2023-04-03\",\"2023-04-04\",\"2023-04-05\",\"2023-04-06\",\"2023-04-10\",\"2023-04-11\",\"2023-04-12\",\"2023-04-13\",\"2023-04-14\",\"2023-04-17\",\"2023-04-18\",\"2023-04-19\",\"2023-04-20\",\"2023-04-21\",\"2023-04-24\",\"2023-04-25\",\"2023-04-26\",\"2023-04-27\",\"2023-04-28\",\"2023-05-01\",\"2023-05-02\",\"2023-05-03\",\"2023-05-04\",\"2023-05-05\",\"2023-05-08\",\"2023-05-09\",\"2023-05-10\",\"2023-05-11\",\"2023-05-12\",\"2023-05-15\",\"2023-05-16\",\"2023-05-17\",\"2023-05-18\",\"2023-05-19\",\"2023-05-22\",\"2023-05-23\",\"2023-05-24\",\"2023-05-25\",\"2023-05-26\",\"2023-05-30\",\"2023-05-31\",\"2023-06-01\",\"2023-06-02\",\"2023-06-05\",\"2023-06-06\",\"2023-06-07\",\"2023-06-08\",\"2023-06-09\",\"2023-06-12\",\"2023-06-13\",\"2023-06-14\",\"2023-06-15\",\"2023-06-16\",\"2023-06-20\",\"2023-06-21\",\"2023-06-22\",\"2023-06-23\",\"2023-06-26\",\"2023-06-27\",\"2023-06-28\",\"2023-06-29\",\"2023-06-30\",\"2023-07-03\",\"2023-07-05\",\"2023-07-06\",\"2023-07-07\",\"2023-07-10\",\"2023-07-11\",\"2023-07-12\",\"2023-07-13\",\"2023-07-14\",\"2023-07-17\",\"2023-07-18\",\"2023-07-19\",\"2023-07-20\",\"2023-07-21\",\"2023-07-24\",\"2023-07-25\",\"2023-07-26\",\"2023-07-27\",\"2023-07-28\",\"2023-07-31\",\"2023-08-01\",\"2023-08-02\",\"2023-08-03\",\"2023-08-04\",\"2023-08-07\",\"2023-08-08\",\"2023-08-09\",\"2023-08-10\",\"2023-08-11\",\"2023-08-14\",\"2023-08-15\",\"2023-08-16\",\"2023-08-17\",\"2023-08-18\",\"2023-08-21\",\"2023-08-22\",\"2023-08-23\",\"2023-08-24\",\"2023-08-25\",\"2023-08-28\",\"2023-08-29\",\"2023-08-30\",\"2023-08-31\",\"2023-09-01\",\"2023-09-05\",\"2023-09-06\",\"2023-09-07\",\"2023-09-08\",\"2023-09-11\",\"2023-09-12\",\"2023-09-13\",\"2023-09-14\",\"2023-09-15\",\"2023-09-18\",\"2023-09-19\",\"2023-09-20\",\"2023-09-21\",\"2023-09-22\",\"2023-09-25\",\"2023-09-26\",\"2023-09-27\",\"2023-09-28\",\"2023-09-29\",\"2023-10-02\",\"2023-10-03\",\"2023-10-04\",\"2023-10-05\",\"2023-10-06\",\"2023-10-09\",\"2023-10-10\",\"2023-10-11\",\"2023-10-12\",\"2023-10-13\",\"2023-10-16\",\"2023-10-17\",\"2023-10-18\",\"2023-10-19\",\"2023-10-20\",\"2023-10-23\",\"2023-10-24\",\"2023-10-25\",\"2023-10-26\",\"2023-10-27\",\"2023-10-30\",\"2023-10-31\",\"2023-11-01\",\"2023-11-02\",\"2023-11-03\",\"2023-11-06\",\"2023-11-07\",\"2023-11-08\",\"2023-11-09\",\"2023-11-10\",\"2023-11-13\",\"2023-11-14\",\"2023-11-15\",\"2023-11-16\",\"2023-11-17\",\"2023-11-20\",\"2023-11-21\",\"2023-11-22\",\"2023-11-24\",\"2023-11-27\",\"2023-11-28\",\"2023-11-29\",\"2023-11-30\",\"2023-12-01\",\"2023-12-04\",\"2023-12-05\",\"2023-12-06\",\"2023-12-07\",\"2023-12-08\",\"2023-12-11\",\"2023-12-12\",\"2023-12-13\",\"2023-12-14\",\"2023-12-15\",\"2023-12-18\",\"2023-12-19\",\"2023-12-20\",\"2023-12-21\",\"2023-12-22\",\"2023-12-26\",\"2023-12-27\",\"2023-12-28\",\"2023-12-29\"],\"y\":[22.0789947509766,22.2379360198975,21.8440399169922,21.6989192962646,21.4224967956543,21.4708690643311,21.4224967956543,20.9871349334717,21.4985160827637,21.2911968231201,21.2082710266113,21.1875419616699,21.1322555541992,21.2220973968506,21.0769748687744,21.1944580078125,21.0907936096191,20.8696575164795,21.0700645446777,20.8489284515381,20.8281993865967,20.7095336914062,20.2418804168701,20.2628211975098,19.9347610473633,20.3116798400879,20.5838985443115,20.3326244354248,20.4931583404541,20.8072605133057,20.6816177368164,20.6257724761963,20.5838985443115,20.9747753143311,20.9119606018066,20.9538326263428,21.3516902923584,21.100414276123,20.7095336914062,20.967794418335,20.9259147644043,20.8630962371826,20.7374572753906,20.7932968139648,20.4931583404541,20.758394241333,20.6536960601807,21.2888736724854,21.0096759796143,20.6187992095947,20.2698020935059,20.4791965484619,20.5559749603271,20.9887351989746,21.2051124572754,21.0724945068359,20.9957160949707,20.7863159179688,20.9747753143311,20.9887351989746,20.6886043548584,20.967794418335,21.4424343109131,21.8891487121582,22.9850063323975,22.8663482666016,22.6848697662354,22.2590847015381,22.3079471588135,22.7127857208252,22.7895679473877,22.6848697662354,22.7616424560547,22.9570827484131,23.1944007873535,23.2013816833496,23.2223243713379,23.1804370880127,23.0687675476074,23.033863067627,22.9710483551025,22.8314456939697,22.8942642211914,23.5224590301514,23.3130645751953,23.4317207336426,23.4387035369873,23.6062202453613,23.5922603607178,23.352819442749,23.3739452362061,23.3739452362061,23.5077514648438,23.2612628936768,23.3598613739014,23.5077514648438,23.7612781524658,23.7119789123535,24.0148010253906,24.1908683776855,24.2472152709961,24.3739719390869,24.4373512268066,24.4725723266602,24.5570755004883,24.4303150177002,24.599328994751,24.5359516143799,24.8246898651123,24.8669452667236,24.8528633117676,24.4655265808105,24.6415901184082,24.5007381439209,24.4725723266602,24.0993137359619,24.2965087890625,24.4725723266602,24.2753791809082,24.359884262085,23.9232521057129,23.8035316467285,24.2542476654053,24.655668258667,24.7965145111084,25.050048828125,25.2190647125244,25.2542839050293,25.1908931732178,25.4373893737793,25.4585132598877,25.5218925476074,25.5711936950684,26.0007801055908,25.895149230957,25.8035869598389,25.8035869598389,25.8317642211914,25.8528938293457,25.8740196228027,25.9021873474121,25.9374027252197,25.9514904022217,25.8247241973877,25.9796504974365,26.2754402160645,25.6275310516357,25.0594577789307,24.9600391387939,25.1659698486328,24.8038120269775,24.910327911377,24.9458332061768,24.9600391387939,24.8393173217773,24.9316368103027,24.7044010162354,24.9529342651367,24.9884338378906,24.8393173217773,24.7399044036865,24.9174327850342,24.7257022857666,24.6902027130127,24.7257022857666,24.9316368103027,24.768310546875,24.7115058898926,24.6262950897217,24.6902027130127,24.6902027130127,24.7399044036865,24.6546936035156,24.2144260406494,24.6049842834473,24.1718311309814,24.1008186340332,24.2428340911865,24.1008186340332,23.894889831543,24.0085067749023,24.3422508239746,24.2499389648438,24.328052520752,23.887788772583,24.0227088928223,24.1363220214844,23.6605567932129,24.0511093139648,23.9161891937256,23.9445972442627,24.0724086761475,23.894889831543,23.8309783935547,23.866491317749,23.525634765625,23.4830322265625,23.2628974914551,23.1918888092041,23.0782718658447,23.2131881713867,23.1492824554443,23.1066741943359,22.8510417938232,22.8155364990234,22.9220504760742,23.0072593688965,23.0640697479248,22.6735134124756,22.5172882080078,22.0628223419189,21.7503852844238,21.2249088287354,21.3030185699463,21.5728569030762,21.5154838562012,23.03590965271,24.0184555053711,23.3729858398438,23.2223739624023,23.1147994995117,22.92116355896,22.7562103271484,22.5769157409668,22.6414604187012,22.4693374633789,22.5338840484619,22.7275199890137,22.619945526123,22.8924732208252,23.0502529144287,22.5625705718994,22.6844902038574,22.6558055877686,22.6342945098877,22.3689289093018,22.1896381378174,22.7346954345703,23.2367210388184,23.5451126098633,23.5379390716553,23.4877338409424,23.5522804260254,23.5451126098633,23.5594539642334,23.2367210388184,23.1936931610107,23.2940979003906,23.3299560546875,23.2008628845215,23.3012733459473,23.2940979003906,23.6670360565186,23.8750171661377,24.1045188903809,24.0112781524658,24.0041084289551,23.9825916290283,23.5451126098633,23.3801651000977,23.3227844238281,22.9928798675537,22.9713687896729,22.7346954345703,22.7848968505859,22.5625705718994,22.3402442932129,22.4406471252441,22.4334754943848,22.5338840484619,22.4549980163574,22.7562103271484,22.944580078125,22.9880504608154,23.2488594055176,23.3502941131592,23.2416191101074,23.2850875854492,23.4589672088623,23.43723487854,23.6255970001221,23.7270259857178,24.2776412963867,24.3573303222656,24.3573303222656,24.3573303222656,24.3355960845947,24.6761093139648,24.821008682251,24.8354930877686,24.7195739746094,24.9369277954102,25.0021286010742,25.0093727111816,24.886209487915,24.6253967285156,24.5674324035645,24.6688652038574,24.7123336791992,24.7123336791992,24.7920265197754,25.0890655517578,24.9441680908203,24.8644771575928,24.9079475402832,24.8137531280518,24.9731483459473,24.8427391052246,24.6326370239258,24.7630443572998,24.748556137085,24.8717136383057,24.886209487915,24.7847862243652,24.806510925293,24.8789672851562,24.7702903747559,24.7123336791992,24.7050800323486,24.66162109375,24.5819225311279,24.5746822357178,24.5457019805908,24.6326370239258,24.5167198181152,24.3500900268555,24.4442710876465,24.3718280792236,24.4442710876465,24.45876121521,24.523962020874,24.5312080383301,24.5746822357178,24.4732513427734,24.3500900268555,24.2486572265625,24.234167098999,24.2558994293213,24.234167098999,24.1834564208984,24.1615085601807,24.1688251495361,24.1468811035156,24.2273426055908,23.8469657897949,23.5763053894043,23.5689907073975,23.7445545196533,23.4958381652832,23.5104675292969,23.4446392059326,23.5251007080078,23.5104675292969,23.5031604766846,23.8835411071777,23.9274272918701,23.8030757904053,23.6640911102295,23.4592685699463,23.4080619812012,23.2251930236816,23.9713191986084,23.9201126098633,23.8323364257812,23.9127998352051,24.0005798339844,24.1176166534424,24.3004932403564,24.5492076873779,24.7832870483398,24.9149589538574,24.9954204559326,24.9003276824951,24.7028198242188,24.6881885528564,24.6004085540771,24.5711498260498,24.7393951416016,24.6077251434326,24.3004932403564,24.3955917358398,24.4394798278809,24.2639198303223,24.3004932403564,24.3443870544434,24.4541034698486,24.3224430084229,24.4029102325439,24.5930938720703,24.5345764160156,24.4906845092773,24.373649597168,24.2127113342285,24.0590991973877,24.1395645141602,24.24928855896,24.2566013336182,24.1980838775635,24.3162689208984,24.6929740905762,24.8480949401855,24.604341506958,24.5821781158447,24.7077503204346,24.6855907440186,24.5600242614746,24.604341506958,24.6560459136963,24.6412792205811,24.3384323120117,24.1316089630127,24.1980876922607,24.4861545562744,24.5526371002197,24.5452480316162,24.6634368896484,24.7225246429443,24.7446880340576,24.7077503204346,25.0549182891846,25.0844631195068,24.9662742614746,25.1066246032715,25.1066246032715,25.1878700256348,25.3503742218018,26.1259574890137,25.8969745635986,26.3918704986572,26.1185665130615,26.2589130401611,26.1850471496582,26.5839138031006,26.569149017334,26.5617542266846,26.229362487793,26.0742473602295,26.1850471496582,26.295841217041,26.3697052001953,26.643009185791,26.6947135925293,26.5617542266846,26.5913066864014,26.6282348632812,26.6947135925293,26.8867588043213,26.9237003326416,26.8498268127441,26.8424415588379,26.576530456543,26.7390289306641,26.4657287597656,26.7685775756836,26.9015350341797,26.8867588043213,26.790735244751,26.7094879150391,26.3992576599121,26.295841217041,25.9634532928467,25.8969745635986,26.0447006225586,26.1924304962158,26.2589130401611,26.0890197753906,26.1185665130615,26.1037940979004,26.2379684448242,26.2230644226074,26.3125057220459,26.3721408843994,26.3572273254395,26.5063076019287,26.3646869659424,26.3497772216797,26.4914016723633,26.4094009399414,26.4541244506836,26.4541244506836,26.7224731445312,26.990816116333,27.0280857086182,27.0951747894287,26.8790111541748,26.5584907531738,26.5063076019287,26.4615859985352,26.6404819488525,26.990816116333,27.2666110992432,27.3113346099854,27.177173614502,27.7287616729736,27.6765766143799,27.5349655151367,27.177173614502,27.0131759643555,26.9386386871338,26.990816116333,27.0802688598633,27.1100730895996,26.9982757568359,27.1622562408447,27.3635196685791,27.4231510162354,27.47532081604,27.1697196960449,27.1399002075195,27.1846179962158,27.2517070770264,27.2367897033691,27.281530380249,27.7138481140137,27.5722274780273,27.5349655151367,27.5275001525879,27.4455108642578,27.5275001525879,27.7511138916016,29.0779304504395,29.0853824615479,28.1760005950928,27.6094989776611,27.70729637146,27.5417881011963,26.0823211669922,26.5412273406982,26.3155384063721,25.2999286651611,25.6986484527588,26.0748023986816,26.2854461669922,26.473518371582,26.8647212982178,27.2784843444824,27.0904121398926,26.9023342132568,26.8872871398926,27.2784843444824,27.9028949737549,27.6847305297852,27.3160991668701,26.8045387268066,27.0452728271484,27.1731643676758,26.9926090240479,27.0302200317383,27.4590358734131,27.6621627807617,27.5417881011963,27.6471080780029,27.3461894989014,27.5192222595215,27.6696872711182,27.3311500549316,27.3311500549316,27.2860088348389,26.7819671630859,25.9469146728516,26.3606758117676,26.3381061553955,26.5562763214111,26.6992073059082,26.368200302124,26.8421478271484,27.1806812286377,26.8797645568848,26.4584712982178,26.6766395568848,27.0452728271484,26.9249038696289,27.3236179351807,27.3236179351807,27.4816017150879,27.3311500549316,27.4515151977539,27.4816017150879,27.5568332672119,27.6847305297852,27.8803253173828,27.5944499969482,27.7223415374756,27.8351879119873,27.5417881011963,26.6315078735352,26.2478313446045,26.1500244140625,26.2102108001709,26.2779197692871,26.3155384063721,26.4584712982178,26.6179981231689,26.9674396514893,27.240909576416,27.1117744445801,27.1041717529297,27.1269645690918,27.0737915039062,27.1953277587891,27.1345596313477,27.3244743347168,27.2636947631836,27.1041717529297,27.1193656921387,27.3852443695068,27.2940845489502,27.5371685028076,27.6890983581543,27.681510925293,27.6359252929688,27.7194938659668,27.8562240600586,27.5751552581787,27.5751552581787,27.5143890380859,27.4688053131104,27.6207294464111,27.4688053131104,27.5143890380859,27.6967029571533,27.5751552581787,27.7346782684326,27.6359252929688,27.6359252929688,27.5067920684814,27.6207294464111,27.5599613189697,27.5979461669922,27.613130569458,28.0081596374512,28.1904735565186,28.2284526824951,28.4335556030273,28.2664356231689,28.501916885376,28.5095272064209,28.3955726623535,28.6006774902344,28.608268737793,28.3803825378418,28.3575820922852,28.2664356231689,28.6386604309082,28.8589572906494,28.988094329834,29.1780128479004,29.3147430419922,30.3326721191406,30.590950012207,30.3764343261719,31.0582809448242,31.4413375854492,31.2881202697754,31.7247982025146,31.4106864929199,31.3570537567139,31.2651386260986,31.1885166168213,31.5332736968994,31.732458114624,32.2457656860352,32.429630279541,32.2993812561035,32.2304344177246,32.3300323486328,32.4832534790039,31.8550338745117,31.7937564849854,31.7937564849854,31.7937564849854,31.8090801239014,31.694149017334,32.061897277832,32.0082588195801,32.3300323486328,32.2227783203125,32.4142990112305,32.4909057617188,32.8280029296875,32.9122734069824,32.9505844116211,33.3336372375488,33.1421127319336,33.5175094604492,33.754997253418,33.655403137207,33.5481491088867,33.4638748168945,33.6324157714844,33.7626609802246,33.9158897399902,33.8775787353516,34.3295936584473,34.2453231811523,34.4061965942383,34.6896667480469,34.8352241516113,34.0997505187988,32.79736328125,33.5404891967773,33.034854888916,33.655403137207,34.1457176208496,33.7090339660645,34.092098236084,33.9924964904785,33.7856483459473,32.5445365905762,33.2570343017578,32.636474609375,33.1191215515137,32.8586387634277,32.9888801574707,33.4562225341797,32.8892936706543,33.3412971496582,32.9505844116211,34.0154876708984,33.8533515930176,34.1853256225586,34.054084777832,33.5985870361328,33.1276550292969,33.3592567443848,33.5908622741699,34.1081275939941,33.6063041687012,33.2743301391602,33.3052139282227,33.4596252441406,34.0231971740723,34.6639823913574,35.1349220275879,35.6907730102539,35.5054931640625,34.8492660522461,34.7257499694824,33.9073944091797,34.2779731750488,33.976879119873,34.0926742553711,34.4092102050781,33.8147583007812,33.282054901123,32.7339172363281,32.4019546508789,32.3865089416504,32.3710670471191,31.3056602478027,32.5717926025391,33.0813331604004,33.1662521362305,33.6989479064941,33.39013671875,32.4559860229492,33.1971397399902,33.3746910095215,33.529109954834,33.4596252441406,32.6644325256348,33.1044921875,32.7107543945312,32.9886856079102,32.5100326538086,32.787956237793,32.8342781066895,32.6335563659668,32.5486259460449,31.61448097229,31.3751487731934,30.5182018280029,31.475513458252,32.1008529663086,33.0587425231934,33.3936157226562,33.0509567260742,32.7939567565918,32.9652862548828,32.4746627807617,32.8874092102051,32.4590873718262,32.6070556640625,32.4746627807617,32.6849365234375,33.0198020935059,33.1755638122559,32.8640518188477,32.8173179626465,33.4559059143066,33.5493659973145,33.5026359558105,33.4325523376465,33.7596321105957,33.7674179077148,33.541576385498,33.4013977050781,32.5992660522461,32.2332458496094,31.8438568115234,32.3189125061035,32.4980239868164,32.7160797119141,32.0774917602539,32.5369567871094,32.5603332519531,32.9419326782227,32.8406829833984,32.9808616638184,32.591480255127,32.6226272583008,33.0353775024414,32.7238655090332,32.9341430664062,33.0743141174316,33.3624649047852,33.4169731140137,33.3624649047852,33.2845878601074,33.4792747497559,33.5960922241211,33.3624649047852,33.2768020629883,32.9185600280762,32.4824562072754,32.7783813476562,31.867223739624,31.0572967529297,30.6679267883301,30.3564147949219,30.6990718841553,30.6601295471191,30.8470401763916,31.1273899078369,30.8314552307129,31.6258087158203,31.7504024505615,31.937313079834,32.2332458496094,32.4357261657715,31.7971363067627,31.8905906677246,31.9298725128174,31.9927310943604,31.874870300293,31.9455871582031,32.3305625915527,32.7155494689941,32.5819854736328,32.6762580871582,32.7391204833984,32.9905319213867,32.9355392456055,32.9591064453125,32.9198226928711,32.7784080505371,32.9198226928711,32.6212692260742,32.9355392456055,33.1791000366211,33.3755111694336,33.5562171936035,33.7212066650391,33.8390617370605,33.5248031616211,33.846923828125,33.3912315368652,33.5955047607422,33.6897926330566,33.8390617370605,34.1768989562988,34.2554664611816,34.3104705810547,34.3811836242676,34.3811836242676,33.7762069702148,34.1219100952148,34.0354843139648,34.389045715332,34.7425918579102,34.8840141296387,34.5068893432617,34.0197639465332,34.074764251709,34.616886138916,33.7683486938477,33.3126564025879,33.5876541137695,33.6662216186523,33.5797920227051,33.8311996459961,33.6033592224121,33.6426544189453,33.8547744750977,33.6976432800293,33.5248031616211,33.8547744750977,32.566276550293,30.4763717651367,30.5156536102295,30.3332633972168,30.1350021362305,29.3102569580078,29.3023242950439,29.008903503418,29.2388858795166,28.8265151977539,28.06520652771,27.9145278930664,27.1532249450684,27.3435497283936,27.4783630371094,27.8986682891846,27.4466419219971,27.6528282165527,27.819356918335,27.2325305938721,27.6290397644043,27.2325305938721,27.819356918335,28.0176181793213,28.1920890808105,28.6441116333008,28.414134979248,28.8185729980469,28.9454574584961,29.2071666717529,29.6433277130127,29.6671123504639,29.5640163421631,29.2706031799316,29.2071666717529,28.9454574584961,28.8502998352051,28.9533920288086,29.0961456298828,28.739278793335,28.5568771362305,28.4696445465088,28.3744812011719,28.7234153747559,28.4934349060059,28.096923828125,27.5180149078369,28.1127796173096,28.4934349060059,28.414134979248,28.096923828125,28.3031101226807,28.382417678833,28.6361808776855,28.7868576049805,28.9454574584961,28.8185729980469,28.9137420654297,28.9137420654297,28.9137420654297,28.8899478912354,29.1595783233643,28.8582286834717,29.1595783233643,29.5640163421631,30.3015422821045,30.5156536102295,30.4284152984619,30.4442844390869,30.1587924957275,29.7226295471191,29.8257274627686,29.5534858703613,29.6655883789062,29.5695018768311,29.6015224456787,29.3052711486816,29.2652359008789,29.8497352600098,29.801700592041,30.1539993286133,29.6655883789062,30.2180557250977,30.6904582977295,30.9707164764404,30.6584453582764,30.9306659698486,30.8425979614258,30.6584453582764,30.466272354126,30.5383415222168,30.4502601623535,30.6584453582764,30.6824607849121,30.8105659484863,30.6023960113525,30.8586082458496,30.6904582977295,31.3390235900879,31.1468620300293,31.1388530731201,31.2029075622559,31.4110870361328,31.4831523895264,31.4591217041016,31.531192779541,31.4831523895264,31.1548690795898,31.371057510376,31.3390235900879,31.1708850860596,31.1308479309082,31.0267601013184,31.274974822998,31.1388530731201,31.619270324707,31.5552082061768,32.0836715698242,32.564079284668,32.5160522460938,32.4359741210938,32.2998542785645,32.1797485351562,32.5961112976074,31.8834972381592,32.1557312011719,30.5383415222168,30.0899524688721,29.9848003387451,30.1223011016846,30.3406982421875,30.4862899780273,30.8745555877686,30.9473533630371,30.7774868011475,30.5833568572998,30.8098411560059,30.5267372131348,29.8715572357178,29.5318260192871,29.3781433105469,29.3053455352783,28.9979801177979,28.8928241729736,28.0435104370117,27.4449462890625,28.0839557647705,27.5824527740479,27.0324192047119,28.2133712768555,27.7442264556885,29.4428539276123,28.6825160980225,28.3266143798828,27.3074398040771,27.9787998199463,26.0213356018066,24.2822647094727,26.4581260681152,24.4116840362549,26.0132465362549,26.1750202178955,24.6058101654053,23.465311050415,23.0446968078613,24.0234279632568,24.063871383667,25.6816082000732,24.9940700531006,26.4257678985596,26.4015026092529,25.6816082000732,26.5875453948975,27.2103748321533,27.9626216888428,27.1861057281494,27.9868850708008,28.6259002685547,28.4236793518066,29.4752140045166,29.0950374603271,29.0222396850586,29.8553733825684,29.1840114593506,28.8119354248047,29.3215198516846,29.6774291992188,30.2355480194092,31.0039672851562,30.6642475128174,30.8341121673584,31.0282402038574,30.4458465576172,30.4296798706055,31.1495761871338,31.1495761871338,30.1937580108643,30.4061584472656,31.1250591278076,30.5205345153809,30.2672824859619,30.978006362915,30.8473014831543,31.1005535125732,30.7819480895996,30.7410984039307,30.4388370513916,30.6348991394043,30.6267318725586,30.5613708496094,31.1904048919678,31.1985836029053,28.9683609008789,29.5402164459229,29.5402164459229,29.4176731109619,29.4013366699219,29.8914985656738,29.5810623168945,29.3441543579102,27.2037925720215,27.5714130401611,27.2528076171875,27.2854862213135,27.4161949157715,27.1547775268555,27.3018226623535,27.0485725402832,26.7708206176758,26.2969970703125,26.4032001495361,26.1744575500488,26.6646194458008,26.7136325836182,27.5632438659668,28.1922779083252,28.1922779083252,27.8001537322998,27.5714130401611,27.3345031738281,27.6367664337158,28.7641296386719,28.7804660797119,29.1807708740234,29.0827312469482,29.6137371063232,29.8179702758789,29.9731922149658,31.5008411407471,31.3783054351807,30.7656078338623,30.6675815582275,31.876636505127,32.0726928710938,31.9572124481201,31.7427291870117,31.6354885101318,31.668493270874,31.7179889678955,31.5695056915283,31.7179889678955,31.668493270874,31.1735439300537,31.618989944458,31.4870090484619,31.3962688446045,31.6354885101318,31.6437435150146,31.5612487792969,31.9407234191895,32.072696685791,32.0397033691406,31.6849918365479,31.3880214691162,31.2312889099121,31.2725276947021,31.1735439300537,30.422872543335,30.6868476867676,30.0269069671631,29.9939098358154,29.6392002105713,29.8454303741455,29.408224105835,29.7546882629395,30.5301074981689,30.4888648986816,30.3403835296631,30.3733730316162,30.2166385650635,29.7134399414062,29.9031753540039,29.6969470977783,29.4989624023438,29.738187789917,30.0186595916748,29.8371810913086,30.2743854522705,30.0021648406982,30.0104103088379,30.3156299591064,29.8371810913086,30.0846557617188,30.4311218261719,30.3486289978027,30.3733730316162,30.4393692016602,30.4063720703125,30.1506481170654,31.3055305480957,31.1817932128906,30.9260711669922,30.587854385376,30.8765754699707,31.4952602386475,31.2807788848877,30.8765754699707,29.2432441711426,29.1030082702637,29.2679882049561,29.8866806030273,29.8536739349365,30.7940788269043,30.3273773193359,30.3357048034668,32.6692314147949,32.2358627319336,32.0858535766602,31.2941188812256,32.1858558654785,31.1107769012451,31.6576156616211,31.9035682678223,31.7893714904785,32.2373580932617,32.0792465209961,32.1495208740234,32.0880317687988,32.7029113769531,33.6515884399414,34.6178283691406,35.838809967041,35.2151412963867,35.4347457885742,36.2340888977051,37.3847999572754,36.7611312866211,36.6557235717773,36.1198883056641,34.4421539306641,34.0029449462891,33.2387390136719,33.4056358337402,33.098201751709,32.8346786499023,32.2724914550781,32.8873748779297,32.7380561828613,32.3427734375,32.5447998046875,32.2724914550781,32.333984375,32.333984375,32.6677780151367,32.3866882324219,32.5535926818848,32.6150741577148,33.1772499084473,32.6589965820312,32.3779029846191,32.2812843322754,32.2373580932617,32.2637100219727,32.0616760253906,32.0441131591797,32.1055946350098,32.7468414306641,32.7731819152832,31.8333053588867,31.8421783447266,31.8776950836182,31.7889022827148,31.069652557373,30.9364547729492,30.9808559417725,31.007495880127,30.9186992645264,31.0518913269043,30.8476600646973,30.572395324707,30.8299026489258,30.8032665252686,30.9808559417725,30.6878318786621,30.5812759399414,30.4214401245117,30.1106567382812,29.9685840606689,30.0307445526123,29.7377166748047,29.9153079986572,29.7554721832275,30.5368728637695,30.3681621551514,30.5368728637695,30.5013599395752,30.5901584625244,31.0163745880127,30.8210258483887,31.0252552032471,31.442590713501,31.8155403137207,31.7800235748291,31.7622661590576,31.5491466522217,31.9664897918701,31.3982028961182,31.6201839447021,31.6734580993652,32.1884803771973,32.5170249938965,32.0641670227051,32.1707229614258,32.2328758239746,32.2151145935059,32.0108871459961,31.8865795135498,31.9309730529785,32.4992713928223,32.8278045654297,32.996524810791,33.0053977966309,33.3872184753418,34.2485389709473,34.5682106018066,34.6570014953613,35.1009788513184,34.3106994628906,34.3284645080566,34.3462181091309,34.1419868469238,34.4616508483887,34.2751808166504,34.319580078125,35.3673667907715,35.473934173584,35.4916877746582,35.1419677734375,35.4916877746582,35.7427635192871,35.2854385375977,35.5903244018555,35.9579734802246,35.8862342834473,35.9669380187988,35.9131355285645,35.7158660888672,35.9759063720703,35.8234710693359,35.6979293823242,35.2675018310547,34.8998565673828,34.6577529907227,34.7294807434082,34.5232429504395,34.7832908630371,34.944694519043,35.1061019897461,34.9626235961914,34.837085723877,35.6979293823242,36.4780616760254,36.0028076171875,35.5365219116211,35.5006561279297,35.240608215332,35.4020156860352,34.8012199401855,35.348201751709,35.5185890197754,35.0164260864258,35.1419677734375,34.9536628723145,35.0792007446289,35.0612678527832,35.1150665283203,35.473747253418,35.6261901855469,35.2316398620605,35.2854385375977,35.1957740783691,35.5185890197754,35.6530876159668,35.5544662475586,35.8234710693359,35.9490013122559,36.1821441650391,36.0028076171875,36.8098449707031,36.7829399108887,37.1864624023438,37.3747711181641,37.491340637207,37.7513885498047,38.9619407653809,38.717643737793,38.7357406616211,39.7762870788574,41.3325996398926,40.8892288208008,40.7716064453125,40.7806549072266,41.6040458679199,43.6037216186523,41.9026374816895,42.7441253662109,43.8661270141602,44.255199432373,45.6214866638184,44.6171264648438,44.1556587219238,44.0832748413086,45.1781234741211,43.7756309509277,42.9884376525879,42.8708038330078,42.1650352478027,42.3098106384277,41.6854820251465,41.6583404541016,42.3821983337402,42.3821983337402,42.3007659912109,42.0835990905762,41.6492881774902,41.251163482666,40.337287902832,40.4549102783203,40.5092010498047,40.2377548217773,39.7129440307617,39.9934539794922,39.7400970458984,39.7672462463379,39.9843978881836,39.7581901550293,39.4234085083008,38.9438514709473,39.3872146606445,38.9167060852051,38.8443183898926,38.3828468322754,38.2923698425293,38.0209274291992,38.6724014282227,38.4099998474121,38.0571136474609,37.8670997619629,37.4780235290527,37.7042274475098,37.5413627624512,37.3875389099121,38.0842590332031,38.7266845703125,38.7809791564941,39.0524291992188,39.043384552002,39.4143600463867,38.8805122375488,39.0705184936523,39.5772285461426,39.4867477416992,41.1244850158691,40.5544357299805,40.025032043457,44.3698310852051,44.1142578125,43.1740989685059,44.744068145752,45.8028869628906,45.3921318054199,45.3191070556641,45.2734718322754,46.4326934814453,46.9255905151367,46.3687934875488,46.7339019775391,46.6243705749512,46.4509468078613,49.2896690368652,47.8292350769043,49.0432167053223,49.9103584289551,48.4134063720703,49.5361175537109,46.9894828796387,47.2085456848145,46.9164619445801,47.5371475219727,48.1760864257812,50.3849983215332,50.6953392028809,53.6709671020508,55.9072570800781,54.2916488647461,55.697322845459,53.8078842163086,54.3555450439453,53.5888214111328,54.0360794067383,52.949878692627,52.5573883056641,53.3058624267578,53.8991622924805,51.7085113525391,49.7734298706055,50.7774887084961,50.0564002990723,50.8596305847168,51.3342781066895,51.7450180053711,51.7085113525391,50.6953392028809,50.1568031311035,49.3900718688965,48.8697967529297,49.3353042602539,48.1852111816406,47.044246673584,47.9570159912109,48.3860206604004,49.0849952697754,49.9679298400879,48.4595985412598,48.8090934753418,49.5356674194336,49.0942039489746,48.7447166442871,48.9378509521484,47.5490951538086,47.3375511169434,46.5373992919922,46.7029495239258,45.8016319274902,45.7924346923828,45.6912651062012,44.9738960266113,44.6335983276367,43.7138862609863,43.106876373291,42.2699356079102,43.8886375427246,43.1712608337402,42.0768013000488,43.8702392578125,43.9898071289062,44.7439651489258,44.1277618408203,43.6311111450195,44.8359375,45.2498092651367,46.2338981628418,48.0549278259277,48.018138885498,48.6711349487305,49.8851470947266,50.133472442627,49.839168548584,48.7815017700195,47.9997444152832,48.3676300048828,48.5423736572266,49.0022277832031,48.5055847167969,48.2296714782715,47.6134643554688,47.4295272827148,46.8501052856445,47.1260185241699,48.6251449584961,50.7312889099121,50.740478515625,49.6000442504883,48.8458862304688,48.8366775512695,48.8550720214844,47.677848815918,46.1511344909668,45.7556533813477,45.1670341491699,44.2657127380371,45.0198822021484,45.0934524536133,45.746452331543,46.4546279907227,45.1302452087402,44.4588623046875,45.3325881958008,45.6728744506836,44.5600204467773,45.1026573181152,44.7347717285156,45.5165252685547,45.4797401428223,46.7221984863281,46.2864151000977,46.981819152832,47.6030502319336,46.7314720153809,46.9632759094238,48.6508026123047,49.0309600830078,49.5223808288574,49.8005409240723,50.0601654052734,49.9859848022461,49.1793098449707,48.5580825805664,48.8455123901367,49.3276672363281,49.3832969665527,50.0323448181152,49.5780143737793,48.0110206604004,46.3327751159668,44.4227104187012,44.4319839477539,44.9790420532227,44.0240135192871,43.1431655883789,44.6081581115723,45.4982795715332,46.4440383911133,47.8348579406738,48.1037445068359,46.9725456237793,47.2321701049805,48.613712310791,48.5024452209473,47.8812141418457,48.9104156494141,49.5316505432129,49.2998504638672,49.0402297973633,48.2521018981934,48.0202903747559,47.6494102478027,47.983211517334,47.0559959411621,47.6308670043945,47.1208992004395,47.3990631103516,47.5010643005371,48.0017547607422,48.4931716918945,48.1686515808105,47.3930969238281,47.1968688964844,47.2903099060059,46.4306526184082,46.5895004272461,46.5895004272461,46.0382041931152,46.3185272216797,46.5147514343262,46.6735992431641,45.122486114502,46.8231086730957,46.4867248535156,46.5895004272461,46.0382041931152,45.3934707641602,45.9260787963867,45.6924743652344,44.8608512878418,44.3188972473145,44.7580718994141,43.748908996582,43.1976089477539,42.8425331115723,42.2632026672363,43.5713691711426,42.7023735046387,42.7584381103516,43.1041717529297,43.9918518066406,44.7020034790039,44.627254486084,43.1602325439453,43.122859954834,42.926628112793,43.0107307434082,42.4594268798828,41.8333778381348,41.0391311645508,41.6464996337891,41.1886405944824,40.9550323486328,41.1979827880859,41.5156784057617,41.2633895874023,40.8896217346191,41.244701385498,41.5437088012695,41.2260131835938,40.2635726928711,39.5440788269043,39.0114707946777,39.1703109741211,39.2730979919434,40.1607894897461,40.048656463623,40.7868423461914,41.1979827880859,40.2822608947754,40.0953788757324,42.0015678405762,42.5528678894043,42.5995941162109,43.038761138916,42.7397575378418,44.3188972473145,43.4966163635254,44.8608512878418,43.9825096130371,43.8882637023926,44.5008354187012,44.3783187866211,44.6233520507812,44.0296325683594,44.6516227722168,44.8589553833008,46.4045181274414,45.7730979919434,45.2830390930176,45.5469169616699,45.4526748657227,45.4055557250977,46.2537307739258,46.0369720458984,46.3762435913086,46.7155113220215,46.6401214599609,47.2432670593262,48.138557434082,47.9783515930176,47.8087120056152,46.8474502563477,47.3469314575195,48.7982482910156,48.7417068481445,49.156364440918,50.0139656066895,51.3427734375,50.5228729248047,48.4401359558105,48.4024429321289,48.3647422790527,48.6851654052734,48.6663093566895,48.8453674316406,48.1856803894043,47.874683380127,48.3741645812988,48.2893524169922,48.3081932067871,47.2432670593262,46.8003273010254,47.9877700805664,45.603458404541,44.8778038024902,44.7175941467285,44.9626197814941,45.0945587158203,43.4264869689941,42.4086799621582,42.370979309082,42.5123405456543,42.3898315429688,42.1353759765625,42.4746475219727,42.0847129821777,41.647216796875,41.4189605712891,41.9991111755371,41.8184127807617,42.1703033447266,41.9040069580078,41.6186866760254,41.4570083618164,41.8279190063477,41.21923828125,41.7328147888184,41.8374328613281,41.5806427001953,41.2002182006836,40.8483238220215,41.0956001281738,40.6105537414551,40.3062171936035,40.2301254272461,39.7070388793945,38.7845077514648,38.5847816467285,38.2138671875,38.6323356628418,39.136402130127,39.0983581542969,38.366039276123,38.1567993164062,37.5290985107422,37.4625205993652,37.9095268249512,37.9475708007812,38.3089714050293,38.3945693969727,38.1377830505371,38.8130416870117,38.6703796386719,38.0521850585938,38.2138671875,38.4135932922363,38.2519111633301,38.0331649780273,38.2804412841797,38.4040794372559,38.8035316467285,39.3266143798828,38.8986320495605,39.5168266296387,39.4692764282227,39.6880149841309,39.7450866699219,39.3456344604492,39.4407424926758,39.174446105957,39.1649360656738,38.5657577514648,38.2709312438965,37.9000129699707,38.2423973083496,37.9570732116699,37.405460357666,36.7397155761719,36.8443298339844,36.986988067627,37.2913284301758,37.1486701965332,36.5685195922852,36.3592834472656,36.6065635681152,36.7777519226074,36.597053527832,36.4258575439453,36.1278419494629,35.9067230224609,35.7240676879883,35.5798645019531,35.3299102783203,35.0703468322754,35.3491401672363,37.252628326416,38.1082382202148,37.1372680664062,36.3681793212891,36.1470642089844,35.5798645019531,36.550838470459,36.550838470459,36.8776969909668,37.156494140625,36.8873100280762,37.3872146606445,37.5794906616211,37.4641265869141,38.3581924438477,38.723503112793,37.8390579223633,38.2139854431152,38.5120086669922,37.8198280334473,37.3968353271484,37.2333984375,36.8200149536133,35.4645004272461,35.0126647949219,34.8876876831055,34.7242546081543,35.2626152038574,35.2337760925293,35.0511169433594,34.2531929016113,34.157054901123,34.3012580871582,34.6281204223633,34.5992813110352,34.666576385498,34.9165229797363,34.4743003845215,34.8396186828613,35.0318908691406,35.3491401672363,35.9547958374023,36.0605430603027,35.6279335021973,35.7721366882324,35.1888961791992,35.0625228881836,35.052806854248,34.6153755187988,34.3626327514648,34.0224113464355,34.0418548583984,34.6834182739258,34.6445350646973,34.8389511108398,34.7223014831543,35.0333671569824,35.0625228881836,34.4015197753906,34.4890022277832,35.490234375,35.636043548584,35.9762687683105,35.8110198974609,35.636043548584,35.1500091552734,35.3638648986816,35.1986122131348,35.1402931213379,34.8972778320312,34.3917999267578,34.7806243896484,34.3917999267578,33.4100074768066,33.3225212097168,33.2933578491211,32.992015838623,33.1961555480957,33.1281089782715,33.1961555480957,33.1183891296387,32.7003974914551,33.0406265258789,32.6809577941895,31.9324607849121,31.7769317626953,32.0588340759277,31.4950332641602,31.2034111022949,31.1936893463135,32.243522644043,32.992015838623,32.9531364440918,32.3796157836914,32.5351486206055,32.2046432495117,32.2726898193359,32.243522644043,32.1852035522461,32.0005073547363,31.2131328582764,32.3407325744629,31.8352565765381,30.5326843261719,30.3188304901123,29.7939109802246,29.9786033630371,29.580057144165,29.871675491333,30.2896671295166,29.2689933776855,29.6967029571533,29.7064247131348,29.6578216552734,29.6481018066406,30.3868751525879,30.3091087341309,30.3771533966064,29.9591636657715,29.2399864196777,29.0429496765137,28.5503635406494,28.8262119293213,29.7424259185791,29.3286514282227,29.4764270782471,29.5355377197266,29.850793838501,29.8704967498779,30.0478286743164,29.6931648254395,29.2498378753662,29.6340560913086,30.0182723999023,28.4814014434814,28.8459167480469,28.6587333679199,28.3631801605225,28.2055511474609,28.353328704834,28.2154026031494,28.1562938690186,26.2647571563721,25.7426147460938,26.2352027893066,26.6588268280029,27.7425193786621,27.2203769683838,27.8902950286865,27.9789619445801,27.9888134002686,28.1858501434326,28.3631801605225,28.3631801605225],\"mode\":\"lines\",\"name\":\"Pfizer Stock Price\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n\n```{.r .cell-code}\ndataTS <-data.frame(\"Y\"=stock$PFE.Adjusted)\ndataTS$Ts<-seq(1:length(stock$PFE.Adjusted))\ndataTS$D <- ifelse(stock$date < as.Date(\"2020-02-20\"), 0, 1)\ndataTS$P<- seq_along(stock$date)\ndataTS$P[stock$date < as.Date(\"2020-02-20\")] <- 0\n\nhead(dataTS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Y Ts D P\n1 22.07899  1 0 0\n2 22.23794  2 0 0\n3 21.84404  3 0 0\n4 21.69892  4 0 0\n5 21.42250  5 0 0\n6 21.47087  6 0 0\n```\n:::\n\n```{.r .cell-code}\nindex_of_2020_02_20 <- which(stock$date == as.Date(\"2020-02-20\"))\n#index_of_2020_02_20 #1040\n\nplot( dataTS$Ts, dataTS$Y,\n      bty=\"n\", pch=19, col=\"gray\",\n      xlab = \"Time (days)\", \n      ylab = \"Pfizer Stock Price\" )\n\n# Line marking the interruption\nabline( v=1039, col=\"firebrick\", lty=2 )\ntext( 700, 40, \"Start of COVID\", col=\"firebrick\", cex=1.3, pos=4 )\n\n# Add the regression line\nts <- lm( Y ~ Ts + D + P, data=dataTS )\nlines( dataTS$Ts, ts$fitted.values, col=\"steelblue\", lwd=2 )\n```\n\n::: {.cell-output-display}\n![](other_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n- **Trend Before COVID-19**: Before the dashed red vertical line that denotes the start of COVID-19, there is a blue line indicating a general upward trend in Pfizer's stock price. This suggests that Pfizer's stock was gradually increasing in value over time before the pandemic began.\n\n- **Start of COVID-19**: The dashed red vertical line indicates the point at which the COVID-19 pandemic started. This is a crucial time marker for the analysis.\n\n- **Trend After COVID-19**: After the start of COVID-19, the plot shows significant volatility in Pfizer's stock price. The stock price initially follows the pre-pandemic trend and continues to increase but then shows some fluctuation before sharply rising. This sharp rise could be due to various factors, potentially including positive news about vaccine development or other pharmaceutical advances related to COVID-19 made by Pfizer.\n\n- **Overall Pattern**: Towards the right end of the plot, after a peak, there is a noticeable decline in the stock price, which may indicate a period of correction or response to other market or global factors.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer( ts, \n           type = \"text\", \n           dep.var.labels = (\"Pfizer Stock Price\"),\n           column.labels = (\"Model results\"),\n           covariate.labels = c(\"Time\", \"Treatment\", \"Time Since Treatment\"),\n           omit.stat = \"all\", \n           digits = 2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================\n                         Dependent variable:    \n                     ---------------------------\n                         Pfizer Stock Price     \n                            Model results       \n------------------------------------------------\nTime                           0.01***          \n                               (0.001)          \n                                                \nTreatment                      2.29**           \n                               (0.92)           \n                                                \nTime Since Treatment          -0.002***         \n                               (0.001)          \n                                                \nConstant                      21.56***          \n                               (0.31)           \n                                                \n================================================\n================================================\nNote:                *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\nThe regression results presented show  impact of the onset of the COVID-19 pandemic on the stock price of Pfizer. The regression model includes variables for time, treatment, and the time since treatment was introduced. Here’s a breakdown of each component of the output:\n\n- **Time (`Ts`)**: The coefficient for time is 0.01 with a p-value of less than 0.01 (indicated by `***`), suggesting that it is highly statistically significant. This implies that, on average, the stock price of Pfizer has been increasing by 0.01 units each time unit regardless of other factors in the model.\n\n- **Treatment (`D`)**: The treatment variable has a coefficient of 2.29 with a p-value of less than 0.05 (`**`), indicating a statistically significant positive effect on the Pfizer stock price. This suggests that the onset of the COVID-19 pandemic led to an average increase in Pfizer’s stock price by 2.29 units at the time of the treatment's implementation.\n\n- **Time Since Treatment (`P`)**: The coefficient for time since treatment is -0.002 with a p-value of less than 0.01 (`***`), which is highly significant. This indicates that following the treatment, the stock price decreases by an average of 0.002 units per time unit. This could suggest that the initial positive impact of the treatment diminishes over time.\n\nThe model suggests that the Pfizer stock price has a general upward trend over time. There was a significant increase in the stock price at the time of treatment, which means the investment of COVID-19 vaccinates could be helpful for the stock price during some periods of COVID-19.  However, the effect of COVID-19 diminishes slightly over time, indicating that while the intervention had a positive immediate impact, its effect lessens as time progresses.\n\n",
    "supporting": [
      "other_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.10.3/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}